// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cron_workflow.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TerminateCronWorkflowRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TerminateCronWorkflowRequest) Reset()         { *m = TerminateCronWorkflowRequest{} }
func (m *TerminateCronWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*TerminateCronWorkflowRequest) ProtoMessage()    {}
func (*TerminateCronWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_989cccaad551a50c, []int{0}
}

func (m *TerminateCronWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TerminateCronWorkflowRequest.Unmarshal(m, b)
}
func (m *TerminateCronWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TerminateCronWorkflowRequest.Marshal(b, m, deterministic)
}
func (m *TerminateCronWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TerminateCronWorkflowRequest.Merge(m, src)
}
func (m *TerminateCronWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_TerminateCronWorkflowRequest.Size(m)
}
func (m *TerminateCronWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TerminateCronWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TerminateCronWorkflowRequest proto.InternalMessageInfo

func (m *TerminateCronWorkflowRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *TerminateCronWorkflowRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetCronWorkflowRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCronWorkflowRequest) Reset()         { *m = GetCronWorkflowRequest{} }
func (m *GetCronWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*GetCronWorkflowRequest) ProtoMessage()    {}
func (*GetCronWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_989cccaad551a50c, []int{1}
}

func (m *GetCronWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCronWorkflowRequest.Unmarshal(m, b)
}
func (m *GetCronWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCronWorkflowRequest.Marshal(b, m, deterministic)
}
func (m *GetCronWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCronWorkflowRequest.Merge(m, src)
}
func (m *GetCronWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_GetCronWorkflowRequest.Size(m)
}
func (m *GetCronWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCronWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCronWorkflowRequest proto.InternalMessageInfo

func (m *GetCronWorkflowRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetCronWorkflowRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateCronWorkflowRequest struct {
	Namespace            string        `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	CronWorkflow         *CronWorkflow `protobuf:"bytes,2,opt,name=cronWorkflow,proto3" json:"cronWorkflow,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateCronWorkflowRequest) Reset()         { *m = CreateCronWorkflowRequest{} }
func (m *CreateCronWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCronWorkflowRequest) ProtoMessage()    {}
func (*CreateCronWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_989cccaad551a50c, []int{2}
}

func (m *CreateCronWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCronWorkflowRequest.Unmarshal(m, b)
}
func (m *CreateCronWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCronWorkflowRequest.Marshal(b, m, deterministic)
}
func (m *CreateCronWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCronWorkflowRequest.Merge(m, src)
}
func (m *CreateCronWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCronWorkflowRequest.Size(m)
}
func (m *CreateCronWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCronWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCronWorkflowRequest proto.InternalMessageInfo

func (m *CreateCronWorkflowRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *CreateCronWorkflowRequest) GetCronWorkflow() *CronWorkflow {
	if m != nil {
		return m.CronWorkflow
	}
	return nil
}

type UpdateCronWorkflowRequest struct {
	Namespace            string        `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CronWorkflow         *CronWorkflow `protobuf:"bytes,3,opt,name=cronWorkflow,proto3" json:"cronWorkflow,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateCronWorkflowRequest) Reset()         { *m = UpdateCronWorkflowRequest{} }
func (m *UpdateCronWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCronWorkflowRequest) ProtoMessage()    {}
func (*UpdateCronWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_989cccaad551a50c, []int{3}
}

func (m *UpdateCronWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCronWorkflowRequest.Unmarshal(m, b)
}
func (m *UpdateCronWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCronWorkflowRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCronWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCronWorkflowRequest.Merge(m, src)
}
func (m *UpdateCronWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCronWorkflowRequest.Size(m)
}
func (m *UpdateCronWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCronWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCronWorkflowRequest proto.InternalMessageInfo

func (m *UpdateCronWorkflowRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *UpdateCronWorkflowRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateCronWorkflowRequest) GetCronWorkflow() *CronWorkflow {
	if m != nil {
		return m.CronWorkflow
	}
	return nil
}

type ListCronWorkflowRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PageSize             int32    `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Page                 int32    `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCronWorkflowRequest) Reset()         { *m = ListCronWorkflowRequest{} }
func (m *ListCronWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*ListCronWorkflowRequest) ProtoMessage()    {}
func (*ListCronWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_989cccaad551a50c, []int{4}
}

func (m *ListCronWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCronWorkflowRequest.Unmarshal(m, b)
}
func (m *ListCronWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCronWorkflowRequest.Marshal(b, m, deterministic)
}
func (m *ListCronWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCronWorkflowRequest.Merge(m, src)
}
func (m *ListCronWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_ListCronWorkflowRequest.Size(m)
}
func (m *ListCronWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCronWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCronWorkflowRequest proto.InternalMessageInfo

func (m *ListCronWorkflowRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ListCronWorkflowRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListCronWorkflowRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type ListCronWorkflowsResponse struct {
	Count                int32           `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	CronWorkflows        []*CronWorkflow `protobuf:"bytes,2,rep,name=cronWorkflows,proto3" json:"cronWorkflows,omitempty"`
	Page                 int32           `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Pages                int32           `protobuf:"varint,4,opt,name=pages,proto3" json:"pages,omitempty"`
	TotalCount           int32           `protobuf:"varint,5,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListCronWorkflowsResponse) Reset()         { *m = ListCronWorkflowsResponse{} }
func (m *ListCronWorkflowsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCronWorkflowsResponse) ProtoMessage()    {}
func (*ListCronWorkflowsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_989cccaad551a50c, []int{5}
}

func (m *ListCronWorkflowsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCronWorkflowsResponse.Unmarshal(m, b)
}
func (m *ListCronWorkflowsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCronWorkflowsResponse.Marshal(b, m, deterministic)
}
func (m *ListCronWorkflowsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCronWorkflowsResponse.Merge(m, src)
}
func (m *ListCronWorkflowsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCronWorkflowsResponse.Size(m)
}
func (m *ListCronWorkflowsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCronWorkflowsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCronWorkflowsResponse proto.InternalMessageInfo

func (m *ListCronWorkflowsResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ListCronWorkflowsResponse) GetCronWorkflows() []*CronWorkflow {
	if m != nil {
		return m.CronWorkflows
	}
	return nil
}

func (m *ListCronWorkflowsResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListCronWorkflowsResponse) GetPages() int32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *ListCronWorkflowsResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type CronWorkflow struct {
	Name                       string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Schedule                   string             `protobuf:"bytes,2,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Timezone                   string             `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Suspend                    bool               `protobuf:"varint,4,opt,name=suspend,proto3" json:"suspend,omitempty"`
	ConcurrencyPolicy          string             `protobuf:"bytes,5,opt,name=concurrencyPolicy,proto3" json:"concurrencyPolicy,omitempty"`
	StartingDeadlineSeconds    int64              `protobuf:"varint,6,opt,name=startingDeadlineSeconds,proto3" json:"startingDeadlineSeconds,omitempty"`
	SuccessfulJobsHistoryLimit int32              `protobuf:"varint,7,opt,name=successfulJobsHistoryLimit,proto3" json:"successfulJobsHistoryLimit,omitempty"`
	FailedJobsHistoryLimit     int32              `protobuf:"varint,8,opt,name=failedJobsHistoryLimit,proto3" json:"failedJobsHistoryLimit,omitempty"`
	WorkflowExecution          *WorkflowExecution `protobuf:"bytes,9,opt,name=workflowExecution,proto3" json:"workflowExecution,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}           `json:"-"`
	XXX_unrecognized           []byte             `json:"-"`
	XXX_sizecache              int32              `json:"-"`
}

func (m *CronWorkflow) Reset()         { *m = CronWorkflow{} }
func (m *CronWorkflow) String() string { return proto.CompactTextString(m) }
func (*CronWorkflow) ProtoMessage()    {}
func (*CronWorkflow) Descriptor() ([]byte, []int) {
	return fileDescriptor_989cccaad551a50c, []int{6}
}

func (m *CronWorkflow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CronWorkflow.Unmarshal(m, b)
}
func (m *CronWorkflow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CronWorkflow.Marshal(b, m, deterministic)
}
func (m *CronWorkflow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CronWorkflow.Merge(m, src)
}
func (m *CronWorkflow) XXX_Size() int {
	return xxx_messageInfo_CronWorkflow.Size(m)
}
func (m *CronWorkflow) XXX_DiscardUnknown() {
	xxx_messageInfo_CronWorkflow.DiscardUnknown(m)
}

var xxx_messageInfo_CronWorkflow proto.InternalMessageInfo

func (m *CronWorkflow) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CronWorkflow) GetSchedule() string {
	if m != nil {
		return m.Schedule
	}
	return ""
}

func (m *CronWorkflow) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *CronWorkflow) GetSuspend() bool {
	if m != nil {
		return m.Suspend
	}
	return false
}

func (m *CronWorkflow) GetConcurrencyPolicy() string {
	if m != nil {
		return m.ConcurrencyPolicy
	}
	return ""
}

func (m *CronWorkflow) GetStartingDeadlineSeconds() int64 {
	if m != nil {
		return m.StartingDeadlineSeconds
	}
	return 0
}

func (m *CronWorkflow) GetSuccessfulJobsHistoryLimit() int32 {
	if m != nil {
		return m.SuccessfulJobsHistoryLimit
	}
	return 0
}

func (m *CronWorkflow) GetFailedJobsHistoryLimit() int32 {
	if m != nil {
		return m.FailedJobsHistoryLimit
	}
	return 0
}

func (m *CronWorkflow) GetWorkflowExecution() *WorkflowExecution {
	if m != nil {
		return m.WorkflowExecution
	}
	return nil
}

func init() {
	proto.RegisterType((*TerminateCronWorkflowRequest)(nil), "api.TerminateCronWorkflowRequest")
	proto.RegisterType((*GetCronWorkflowRequest)(nil), "api.GetCronWorkflowRequest")
	proto.RegisterType((*CreateCronWorkflowRequest)(nil), "api.CreateCronWorkflowRequest")
	proto.RegisterType((*UpdateCronWorkflowRequest)(nil), "api.UpdateCronWorkflowRequest")
	proto.RegisterType((*ListCronWorkflowRequest)(nil), "api.ListCronWorkflowRequest")
	proto.RegisterType((*ListCronWorkflowsResponse)(nil), "api.ListCronWorkflowsResponse")
	proto.RegisterType((*CronWorkflow)(nil), "api.CronWorkflow")
}

func init() { proto.RegisterFile("cron_workflow.proto", fileDescriptor_989cccaad551a50c) }

var fileDescriptor_989cccaad551a50c = []byte{
	// 704 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xdf, 0x4e, 0x13, 0x41,
	0x14, 0xc6, 0xb3, 0x94, 0x42, 0x7b, 0x44, 0x4d, 0x07, 0x2d, 0xcb, 0xd2, 0x90, 0xba, 0x37, 0x36,
	0xc4, 0xb4, 0x80, 0x11, 0xfc, 0x13, 0x49, 0x0c, 0x10, 0x0d, 0xe1, 0x82, 0x2c, 0x1a, 0x2e, 0xc9,
	0x76, 0x7a, 0x5a, 0x27, 0x6e, 0x67, 0xd6, 0x9d, 0x59, 0xb0, 0x18, 0x6e, 0xd4, 0x78, 0xe7, 0x95,
	0xf1, 0xc6, 0xe7, 0xf0, 0x1d, 0x7c, 0x00, 0x5f, 0xc1, 0x07, 0x31, 0x3b, 0xbb, 0x2d, 0x6d, 0xb7,
	0x25, 0x95, 0x70, 0xd5, 0x3d, 0xf3, 0xcd, 0xcc, 0xf7, 0xeb, 0x99, 0x39, 0x67, 0x60, 0x9e, 0x06,
	0x82, 0x1f, 0x9f, 0x8a, 0xe0, 0x5d, 0xd3, 0x13, 0xa7, 0x55, 0x3f, 0x10, 0x4a, 0x90, 0x8c, 0xeb,
	0x33, 0xab, 0xd4, 0x12, 0xa2, 0xe5, 0x61, 0xcd, 0xf5, 0x59, 0xcd, 0xe5, 0x5c, 0x28, 0x57, 0x31,
	0xc1, 0x65, 0x3c, 0xc5, 0x5a, 0x4a, 0x54, 0x1d, 0xd5, 0xc3, 0x66, 0x0d, 0xdb, 0xbe, 0xea, 0x24,
	0xe2, 0x42, 0x77, 0xbf, 0x63, 0x85, 0x6d, 0xdf, 0x73, 0x15, 0x26, 0xc2, 0xad, 0x41, 0x23, 0x6b,
	0xae, 0x8d, 0x2a, 0x60, 0x34, 0x8e, 0xec, 0x03, 0x28, 0xbd, 0xc6, 0xa0, 0xcd, 0xb8, 0xab, 0x70,
	0x3b, 0x10, 0xfc, 0x28, 0x99, 0xec, 0xe0, 0xfb, 0x10, 0xa5, 0x22, 0x25, 0xc8, 0x73, 0xb7, 0x8d,
	0xd2, 0x77, 0x29, 0x9a, 0x46, 0xd9, 0xa8, 0xe4, 0x9d, 0x8b, 0x01, 0x42, 0x60, 0x3a, 0x0a, 0xcc,
	0x29, 0x2d, 0xe8, 0x6f, 0x7b, 0x0f, 0x8a, 0x2f, 0x51, 0x5d, 0xcf, 0x5e, 0x3e, 0x2c, 0x6e, 0x07,
	0x78, 0x25, 0xb4, 0x47, 0x30, 0x47, 0xfb, 0x16, 0xe9, 0x6d, 0x6f, 0xac, 0x17, 0xaa, 0xae, 0xcf,
	0xaa, 0x03, 0xbb, 0x0d, 0x4c, 0xb3, 0xbf, 0x18, 0xb0, 0xf8, 0xc6, 0x6f, 0x5c, 0x57, 0x36, 0x52,
	0x18, 0x99, 0xc9, 0x30, 0x5a, 0xb0, 0xb0, 0xcf, 0xe4, 0x15, 0xb2, 0x68, 0x41, 0xce, 0x77, 0x5b,
	0x78, 0xc8, 0xce, 0xd0, 0x9c, 0x2e, 0x1b, 0x95, 0xac, 0xd3, 0x8b, 0x23, 0xbe, 0xe8, 0xdb, 0xcc,
	0xea, 0x71, 0xfd, 0x6d, 0xff, 0x32, 0x60, 0x71, 0xd8, 0x49, 0x3a, 0x28, 0x7d, 0xc1, 0x25, 0x92,
	0x3b, 0x90, 0xa5, 0x22, 0xe4, 0x4a, 0xfb, 0x64, 0x9d, 0x38, 0x20, 0x9b, 0x70, 0xb3, 0x1f, 0x56,
	0x9a, 0x53, 0xe5, 0xcc, 0xe8, 0x3f, 0x35, 0x38, 0xaf, 0x07, 0x90, 0xb9, 0x00, 0x88, 0x2c, 0xa2,
	0x5f, 0x99, 0xd0, 0xc6, 0x01, 0x59, 0x06, 0x50, 0x42, 0xb9, 0xde, 0xb6, 0x76, 0x8f, 0x81, 0xfb,
	0x46, 0xec, 0x9f, 0x19, 0x98, 0xeb, 0x77, 0xea, 0xe5, 0xde, 0xe8, 0xcb, 0xbd, 0x05, 0x39, 0x49,
	0xdf, 0x62, 0x23, 0xf4, 0xba, 0x67, 0xd2, 0x8b, 0x23, 0x4d, 0xb1, 0x36, 0x9e, 0x09, 0x1e, 0xe3,
	0xe4, 0x9d, 0x5e, 0x4c, 0x4c, 0x98, 0x95, 0xa1, 0xf4, 0x91, 0x37, 0x34, 0x54, 0xce, 0xe9, 0x86,
	0xe4, 0x01, 0x14, 0xa8, 0xe0, 0x34, 0x0c, 0x02, 0xe4, 0xb4, 0x73, 0x20, 0x3c, 0x46, 0x3b, 0x9a,
	0x2e, 0xef, 0xa4, 0x05, 0xf2, 0x18, 0x16, 0xa4, 0x72, 0x03, 0xc5, 0x78, 0x6b, 0x07, 0xdd, 0x86,
	0xc7, 0x38, 0x1e, 0x22, 0x15, 0xbc, 0x21, 0xcd, 0x99, 0xb2, 0x51, 0xc9, 0x38, 0xe3, 0x64, 0xb2,
	0x05, 0x96, 0x0c, 0x29, 0x45, 0x29, 0x9b, 0xa1, 0xb7, 0x27, 0xea, 0xf2, 0x15, 0x93, 0x4a, 0x04,
	0x9d, 0x7d, 0xd6, 0x66, 0xca, 0x9c, 0xd5, 0xe9, 0xb8, 0x64, 0x06, 0xd9, 0x80, 0x62, 0xd3, 0x65,
	0x1e, 0x36, 0x52, 0x6b, 0x73, 0x7a, 0xed, 0x18, 0x95, 0xec, 0x40, 0xa1, 0xdb, 0x2d, 0x76, 0x3f,
	0x20, 0x0d, 0xa3, 0xee, 0x63, 0xe6, 0xf5, 0x95, 0x2d, 0xea, 0xd3, 0x3d, 0x1a, 0x56, 0x9d, 0xf4,
	0x82, 0xf5, 0xdf, 0x59, 0x98, 0xef, 0x3f, 0x9c, 0x43, 0x0c, 0x4e, 0x18, 0x45, 0xf2, 0xd5, 0x00,
	0x92, 0x2e, 0x67, 0xb2, 0x9c, 0xdc, 0x9b, 0x31, 0x75, 0x6e, 0xa5, 0xef, 0x95, 0xfd, 0xfc, 0xd3,
	0x9f, 0xbf, 0xdf, 0xa7, 0x36, 0xed, 0xfb, 0x51, 0xa7, 0x94, 0xb5, 0x93, 0xb5, 0x3a, 0x2a, 0x77,
	0xad, 0xf6, 0xb1, 0x57, 0x07, 0xe7, 0xb5, 0x81, 0x1e, 0xfb, 0x74, 0xa0, 0xba, 0xc8, 0x37, 0x03,
	0x48, 0xba, 0xc8, 0x13, 0x90, 0xb1, 0xd5, 0x3f, 0x0a, 0x64, 0x47, 0x83, 0x6c, 0xd9, 0xd5, 0x09,
	0x41, 0x62, 0xe5, 0x7c, 0x88, 0xa7, 0x03, 0xb7, 0x87, 0x5a, 0x26, 0x59, 0xd2, 0x5e, 0xa3, 0x1b,
	0xe9, 0x28, 0x90, 0x0d, 0x0d, 0xb2, 0x4a, 0xfe, 0x13, 0x84, 0x7c, 0x36, 0xa0, 0x90, 0xaa, 0x7f,
	0x52, 0xd2, 0x06, 0x63, 0x3a, 0x90, 0xb5, 0x3c, 0x52, 0xed, 0x75, 0x0d, 0x7b, 0x55, 0xb3, 0xac,
	0x90, 0xca, 0x84, 0x2c, 0x92, 0xfc, 0x30, 0xe0, 0xee, 0xc8, 0x67, 0x88, 0xdc, 0xd3, 0x5e, 0x97,
	0x3d, 0x51, 0x56, 0xb1, 0x1a, 0xbf, 0x8b, 0xd5, 0xee, 0xbb, 0x58, 0xdd, 0x8d, 0xde, 0x45, 0xfb,
	0x85, 0xc6, 0x78, 0xb6, 0xf2, 0x64, 0x52, 0x8c, 0x24, 0x27, 0x35, 0xd5, 0x75, 0xab, 0xcf, 0xe8,
	0x2d, 0x1f, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x68, 0x13, 0xb5, 0xa6, 0xb2, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CronWorkflowServiceClient is the client API for CronWorkflowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CronWorkflowServiceClient interface {
	CreateCronWorkflow(ctx context.Context, in *CreateCronWorkflowRequest, opts ...grpc.CallOption) (*CronWorkflow, error)
	UpdateCronWorkflow(ctx context.Context, in *UpdateCronWorkflowRequest, opts ...grpc.CallOption) (*CronWorkflow, error)
	GetCronWorkflow(ctx context.Context, in *GetCronWorkflowRequest, opts ...grpc.CallOption) (*CronWorkflow, error)
	ListCronWorkflows(ctx context.Context, in *ListCronWorkflowRequest, opts ...grpc.CallOption) (*ListCronWorkflowsResponse, error)
	TerminateCronWorkflow(ctx context.Context, in *TerminateCronWorkflowRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type cronWorkflowServiceClient struct {
	cc *grpc.ClientConn
}

func NewCronWorkflowServiceClient(cc *grpc.ClientConn) CronWorkflowServiceClient {
	return &cronWorkflowServiceClient{cc}
}

func (c *cronWorkflowServiceClient) CreateCronWorkflow(ctx context.Context, in *CreateCronWorkflowRequest, opts ...grpc.CallOption) (*CronWorkflow, error) {
	out := new(CronWorkflow)
	err := c.cc.Invoke(ctx, "/api.CronWorkflowService/CreateCronWorkflow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronWorkflowServiceClient) UpdateCronWorkflow(ctx context.Context, in *UpdateCronWorkflowRequest, opts ...grpc.CallOption) (*CronWorkflow, error) {
	out := new(CronWorkflow)
	err := c.cc.Invoke(ctx, "/api.CronWorkflowService/UpdateCronWorkflow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronWorkflowServiceClient) GetCronWorkflow(ctx context.Context, in *GetCronWorkflowRequest, opts ...grpc.CallOption) (*CronWorkflow, error) {
	out := new(CronWorkflow)
	err := c.cc.Invoke(ctx, "/api.CronWorkflowService/GetCronWorkflow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronWorkflowServiceClient) ListCronWorkflows(ctx context.Context, in *ListCronWorkflowRequest, opts ...grpc.CallOption) (*ListCronWorkflowsResponse, error) {
	out := new(ListCronWorkflowsResponse)
	err := c.cc.Invoke(ctx, "/api.CronWorkflowService/ListCronWorkflows", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronWorkflowServiceClient) TerminateCronWorkflow(ctx context.Context, in *TerminateCronWorkflowRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.CronWorkflowService/TerminateCronWorkflow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CronWorkflowServiceServer is the server API for CronWorkflowService service.
type CronWorkflowServiceServer interface {
	CreateCronWorkflow(context.Context, *CreateCronWorkflowRequest) (*CronWorkflow, error)
	UpdateCronWorkflow(context.Context, *UpdateCronWorkflowRequest) (*CronWorkflow, error)
	GetCronWorkflow(context.Context, *GetCronWorkflowRequest) (*CronWorkflow, error)
	ListCronWorkflows(context.Context, *ListCronWorkflowRequest) (*ListCronWorkflowsResponse, error)
	TerminateCronWorkflow(context.Context, *TerminateCronWorkflowRequest) (*empty.Empty, error)
}

// UnimplementedCronWorkflowServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCronWorkflowServiceServer struct {
}

func (*UnimplementedCronWorkflowServiceServer) CreateCronWorkflow(ctx context.Context, req *CreateCronWorkflowRequest) (*CronWorkflow, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCronWorkflow not implemented")
}
func (*UnimplementedCronWorkflowServiceServer) UpdateCronWorkflow(ctx context.Context, req *UpdateCronWorkflowRequest) (*CronWorkflow, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCronWorkflow not implemented")
}
func (*UnimplementedCronWorkflowServiceServer) GetCronWorkflow(ctx context.Context, req *GetCronWorkflowRequest) (*CronWorkflow, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCronWorkflow not implemented")
}
func (*UnimplementedCronWorkflowServiceServer) ListCronWorkflows(ctx context.Context, req *ListCronWorkflowRequest) (*ListCronWorkflowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCronWorkflows not implemented")
}
func (*UnimplementedCronWorkflowServiceServer) TerminateCronWorkflow(ctx context.Context, req *TerminateCronWorkflowRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TerminateCronWorkflow not implemented")
}

func RegisterCronWorkflowServiceServer(s *grpc.Server, srv CronWorkflowServiceServer) {
	s.RegisterService(&_CronWorkflowService_serviceDesc, srv)
}

func _CronWorkflowService_CreateCronWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCronWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronWorkflowServiceServer).CreateCronWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CronWorkflowService/CreateCronWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronWorkflowServiceServer).CreateCronWorkflow(ctx, req.(*CreateCronWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronWorkflowService_UpdateCronWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCronWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronWorkflowServiceServer).UpdateCronWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CronWorkflowService/UpdateCronWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronWorkflowServiceServer).UpdateCronWorkflow(ctx, req.(*UpdateCronWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronWorkflowService_GetCronWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCronWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronWorkflowServiceServer).GetCronWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CronWorkflowService/GetCronWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronWorkflowServiceServer).GetCronWorkflow(ctx, req.(*GetCronWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronWorkflowService_ListCronWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCronWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronWorkflowServiceServer).ListCronWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CronWorkflowService/ListCronWorkflows",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronWorkflowServiceServer).ListCronWorkflows(ctx, req.(*ListCronWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronWorkflowService_TerminateCronWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateCronWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronWorkflowServiceServer).TerminateCronWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CronWorkflowService/TerminateCronWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronWorkflowServiceServer).TerminateCronWorkflow(ctx, req.(*TerminateCronWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CronWorkflowService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.CronWorkflowService",
	HandlerType: (*CronWorkflowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCronWorkflow",
			Handler:    _CronWorkflowService_CreateCronWorkflow_Handler,
		},
		{
			MethodName: "UpdateCronWorkflow",
			Handler:    _CronWorkflowService_UpdateCronWorkflow_Handler,
		},
		{
			MethodName: "GetCronWorkflow",
			Handler:    _CronWorkflowService_GetCronWorkflow_Handler,
		},
		{
			MethodName: "ListCronWorkflows",
			Handler:    _CronWorkflowService_ListCronWorkflows_Handler,
		},
		{
			MethodName: "TerminateCronWorkflow",
			Handler:    _CronWorkflowService_TerminateCronWorkflow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cron_workflow.proto",
}
