// Code generated by protoc-gen-go. DO NOT EDIT.
// source: secret.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddSecretValueRequest struct {
	Namespace            string         `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SecretName           string         `protobuf:"bytes,2,opt,name=secretName,proto3" json:"secretName,omitempty"`
	AddSecretBody        *AddSecretBody `protobuf:"bytes,3,opt,name=addSecretBody,proto3" json:"addSecretBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddSecretValueRequest) Reset()         { *m = AddSecretValueRequest{} }
func (m *AddSecretValueRequest) String() string { return proto.CompactTextString(m) }
func (*AddSecretValueRequest) ProtoMessage()    {}
func (*AddSecretValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6acf428160d7a216, []int{0}
}

func (m *AddSecretValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSecretValueRequest.Unmarshal(m, b)
}
func (m *AddSecretValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSecretValueRequest.Marshal(b, m, deterministic)
}
func (m *AddSecretValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSecretValueRequest.Merge(m, src)
}
func (m *AddSecretValueRequest) XXX_Size() int {
	return xxx_messageInfo_AddSecretValueRequest.Size(m)
}
func (m *AddSecretValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSecretValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddSecretValueRequest proto.InternalMessageInfo

func (m *AddSecretValueRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *AddSecretValueRequest) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

func (m *AddSecretValueRequest) GetAddSecretBody() *AddSecretBody {
	if m != nil {
		return m.AddSecretBody
	}
	return nil
}

type AddSecretValueResponse struct {
	Inserted             bool     `protobuf:"varint,1,opt,name=inserted,proto3" json:"inserted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSecretValueResponse) Reset()         { *m = AddSecretValueResponse{} }
func (m *AddSecretValueResponse) String() string { return proto.CompactTextString(m) }
func (*AddSecretValueResponse) ProtoMessage()    {}
func (*AddSecretValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6acf428160d7a216, []int{1}
}

func (m *AddSecretValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSecretValueResponse.Unmarshal(m, b)
}
func (m *AddSecretValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSecretValueResponse.Marshal(b, m, deterministic)
}
func (m *AddSecretValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSecretValueResponse.Merge(m, src)
}
func (m *AddSecretValueResponse) XXX_Size() int {
	return xxx_messageInfo_AddSecretValueResponse.Size(m)
}
func (m *AddSecretValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSecretValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddSecretValueResponse proto.InternalMessageInfo

func (m *AddSecretValueResponse) GetInserted() bool {
	if m != nil {
		return m.Inserted
	}
	return false
}

type AddSecretBody struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSecretBody) Reset()         { *m = AddSecretBody{} }
func (m *AddSecretBody) String() string { return proto.CompactTextString(m) }
func (*AddSecretBody) ProtoMessage()    {}
func (*AddSecretBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_6acf428160d7a216, []int{2}
}

func (m *AddSecretBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSecretBody.Unmarshal(m, b)
}
func (m *AddSecretBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSecretBody.Marshal(b, m, deterministic)
}
func (m *AddSecretBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSecretBody.Merge(m, src)
}
func (m *AddSecretBody) XXX_Size() int {
	return xxx_messageInfo_AddSecretBody.Size(m)
}
func (m *AddSecretBody) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSecretBody.DiscardUnknown(m)
}

var xxx_messageInfo_AddSecretBody proto.InternalMessageInfo

func (m *AddSecretBody) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AddSecretBody) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SecretExistsRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SecretName           string   `protobuf:"bytes,2,opt,name=secretName,proto3" json:"secretName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecretExistsRequest) Reset()         { *m = SecretExistsRequest{} }
func (m *SecretExistsRequest) String() string { return proto.CompactTextString(m) }
func (*SecretExistsRequest) ProtoMessage()    {}
func (*SecretExistsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6acf428160d7a216, []int{3}
}

func (m *SecretExistsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretExistsRequest.Unmarshal(m, b)
}
func (m *SecretExistsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretExistsRequest.Marshal(b, m, deterministic)
}
func (m *SecretExistsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretExistsRequest.Merge(m, src)
}
func (m *SecretExistsRequest) XXX_Size() int {
	return xxx_messageInfo_SecretExistsRequest.Size(m)
}
func (m *SecretExistsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretExistsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SecretExistsRequest proto.InternalMessageInfo

func (m *SecretExistsRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *SecretExistsRequest) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

type SecretExistsResponse struct {
	Exists               bool     `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecretExistsResponse) Reset()         { *m = SecretExistsResponse{} }
func (m *SecretExistsResponse) String() string { return proto.CompactTextString(m) }
func (*SecretExistsResponse) ProtoMessage()    {}
func (*SecretExistsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6acf428160d7a216, []int{4}
}

func (m *SecretExistsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretExistsResponse.Unmarshal(m, b)
}
func (m *SecretExistsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretExistsResponse.Marshal(b, m, deterministic)
}
func (m *SecretExistsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretExistsResponse.Merge(m, src)
}
func (m *SecretExistsResponse) XXX_Size() int {
	return xxx_messageInfo_SecretExistsResponse.Size(m)
}
func (m *SecretExistsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretExistsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SecretExistsResponse proto.InternalMessageInfo

func (m *SecretExistsResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

type UpdateSecretKeyValueRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SecretName           string   `protobuf:"bytes,2,opt,name=secretName,proto3" json:"secretName,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSecretKeyValueRequest) Reset()         { *m = UpdateSecretKeyValueRequest{} }
func (m *UpdateSecretKeyValueRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSecretKeyValueRequest) ProtoMessage()    {}
func (*UpdateSecretKeyValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6acf428160d7a216, []int{5}
}

func (m *UpdateSecretKeyValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSecretKeyValueRequest.Unmarshal(m, b)
}
func (m *UpdateSecretKeyValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSecretKeyValueRequest.Marshal(b, m, deterministic)
}
func (m *UpdateSecretKeyValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSecretKeyValueRequest.Merge(m, src)
}
func (m *UpdateSecretKeyValueRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSecretKeyValueRequest.Size(m)
}
func (m *UpdateSecretKeyValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSecretKeyValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSecretKeyValueRequest proto.InternalMessageInfo

func (m *UpdateSecretKeyValueRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *UpdateSecretKeyValueRequest) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

func (m *UpdateSecretKeyValueRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UpdateSecretKeyValueRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type UpdateSecretKeyValueResponse struct {
	Updated              bool     `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSecretKeyValueResponse) Reset()         { *m = UpdateSecretKeyValueResponse{} }
func (m *UpdateSecretKeyValueResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSecretKeyValueResponse) ProtoMessage()    {}
func (*UpdateSecretKeyValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6acf428160d7a216, []int{6}
}

func (m *UpdateSecretKeyValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSecretKeyValueResponse.Unmarshal(m, b)
}
func (m *UpdateSecretKeyValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSecretKeyValueResponse.Marshal(b, m, deterministic)
}
func (m *UpdateSecretKeyValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSecretKeyValueResponse.Merge(m, src)
}
func (m *UpdateSecretKeyValueResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateSecretKeyValueResponse.Size(m)
}
func (m *UpdateSecretKeyValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSecretKeyValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSecretKeyValueResponse proto.InternalMessageInfo

func (m *UpdateSecretKeyValueResponse) GetUpdated() bool {
	if m != nil {
		return m.Updated
	}
	return false
}

type DeleteSecretRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SecretName           string   `protobuf:"bytes,2,opt,name=secretName,proto3" json:"secretName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSecretRequest) Reset()         { *m = DeleteSecretRequest{} }
func (m *DeleteSecretRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSecretRequest) ProtoMessage()    {}
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6acf428160d7a216, []int{7}
}

func (m *DeleteSecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSecretRequest.Unmarshal(m, b)
}
func (m *DeleteSecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSecretRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSecretRequest.Merge(m, src)
}
func (m *DeleteSecretRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSecretRequest.Size(m)
}
func (m *DeleteSecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSecretRequest proto.InternalMessageInfo

func (m *DeleteSecretRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DeleteSecretRequest) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

type DeleteSecretKeyRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SecretName           string   `protobuf:"bytes,2,opt,name=secretName,proto3" json:"secretName,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSecretKeyRequest) Reset()         { *m = DeleteSecretKeyRequest{} }
func (m *DeleteSecretKeyRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSecretKeyRequest) ProtoMessage()    {}
func (*DeleteSecretKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6acf428160d7a216, []int{8}
}

func (m *DeleteSecretKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSecretKeyRequest.Unmarshal(m, b)
}
func (m *DeleteSecretKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSecretKeyRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSecretKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSecretKeyRequest.Merge(m, src)
}
func (m *DeleteSecretKeyRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSecretKeyRequest.Size(m)
}
func (m *DeleteSecretKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSecretKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSecretKeyRequest proto.InternalMessageInfo

func (m *DeleteSecretKeyRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DeleteSecretKeyRequest) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

func (m *DeleteSecretKeyRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DeleteSecretKeyResponse struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSecretKeyResponse) Reset()         { *m = DeleteSecretKeyResponse{} }
func (m *DeleteSecretKeyResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSecretKeyResponse) ProtoMessage()    {}
func (*DeleteSecretKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6acf428160d7a216, []int{9}
}

func (m *DeleteSecretKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSecretKeyResponse.Unmarshal(m, b)
}
func (m *DeleteSecretKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSecretKeyResponse.Marshal(b, m, deterministic)
}
func (m *DeleteSecretKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSecretKeyResponse.Merge(m, src)
}
func (m *DeleteSecretKeyResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSecretKeyResponse.Size(m)
}
func (m *DeleteSecretKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSecretKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSecretKeyResponse proto.InternalMessageInfo

func (m *DeleteSecretKeyResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type DeleteSecretResponse struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSecretResponse) Reset()         { *m = DeleteSecretResponse{} }
func (m *DeleteSecretResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSecretResponse) ProtoMessage()    {}
func (*DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6acf428160d7a216, []int{10}
}

func (m *DeleteSecretResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSecretResponse.Unmarshal(m, b)
}
func (m *DeleteSecretResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSecretResponse.Marshal(b, m, deterministic)
}
func (m *DeleteSecretResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSecretResponse.Merge(m, src)
}
func (m *DeleteSecretResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSecretResponse.Size(m)
}
func (m *DeleteSecretResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSecretResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSecretResponse proto.InternalMessageInfo

func (m *DeleteSecretResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type GetSecretRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SecretName           string   `protobuf:"bytes,2,opt,name=secretName,proto3" json:"secretName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSecretRequest) Reset()         { *m = GetSecretRequest{} }
func (m *GetSecretRequest) String() string { return proto.CompactTextString(m) }
func (*GetSecretRequest) ProtoMessage()    {}
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6acf428160d7a216, []int{11}
}

func (m *GetSecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSecretRequest.Unmarshal(m, b)
}
func (m *GetSecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSecretRequest.Marshal(b, m, deterministic)
}
func (m *GetSecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSecretRequest.Merge(m, src)
}
func (m *GetSecretRequest) XXX_Size() int {
	return xxx_messageInfo_GetSecretRequest.Size(m)
}
func (m *GetSecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSecretRequest proto.InternalMessageInfo

func (m *GetSecretRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetSecretRequest) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

type GetSecretsRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSecretsRequest) Reset()         { *m = GetSecretsRequest{} }
func (m *GetSecretsRequest) String() string { return proto.CompactTextString(m) }
func (*GetSecretsRequest) ProtoMessage()    {}
func (*GetSecretsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6acf428160d7a216, []int{12}
}

func (m *GetSecretsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSecretsRequest.Unmarshal(m, b)
}
func (m *GetSecretsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSecretsRequest.Marshal(b, m, deterministic)
}
func (m *GetSecretsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSecretsRequest.Merge(m, src)
}
func (m *GetSecretsRequest) XXX_Size() int {
	return xxx_messageInfo_GetSecretsRequest.Size(m)
}
func (m *GetSecretsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSecretsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSecretsRequest proto.InternalMessageInfo

func (m *GetSecretsRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type CreateSecretRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Secret               *Secret  `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSecretRequest) Reset()         { *m = CreateSecretRequest{} }
func (m *CreateSecretRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSecretRequest) ProtoMessage()    {}
func (*CreateSecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6acf428160d7a216, []int{13}
}

func (m *CreateSecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSecretRequest.Unmarshal(m, b)
}
func (m *CreateSecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSecretRequest.Marshal(b, m, deterministic)
}
func (m *CreateSecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSecretRequest.Merge(m, src)
}
func (m *CreateSecretRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSecretRequest.Size(m)
}
func (m *CreateSecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSecretRequest proto.InternalMessageInfo

func (m *CreateSecretRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *CreateSecretRequest) GetSecret() *Secret {
	if m != nil {
		return m.Secret
	}
	return nil
}

type GetSecretRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSecretRequest) Reset()         { *m = GetSecretRequest{} }
func (m *GetSecretRequest) String() string { return proto.CompactTextString(m) }
func (*GetSecretRequest) ProtoMessage()    {}
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6acf428160d7a216, []int{1}
}

func (m *GetSecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSecretRequest.Unmarshal(m, b)
}
func (m *GetSecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSecretRequest.Marshal(b, m, deterministic)
}
func (m *GetSecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSecretRequest.Merge(m, src)
}
func (m *GetSecretRequest) XXX_Size() int {
	return xxx_messageInfo_GetSecretRequest.Size(m)
}
func (m *GetSecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSecretRequest proto.InternalMessageInfo

func (m *GetSecretRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetSecretRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Secret struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data                 map[string]string `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Secret) Reset()         { *m = Secret{} }
func (m *Secret) String() string { return proto.CompactTextString(m) }
func (*Secret) ProtoMessage()    {}
func (*Secret) Descriptor() ([]byte, []int) {
	return fileDescriptor_6acf428160d7a216, []int{2}
}

func (m *Secret) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Secret.Unmarshal(m, b)
}
func (m *Secret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Secret.Marshal(b, m, deterministic)
}
func (m *Secret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Secret.Merge(m, src)
}
func (m *Secret) XXX_Size() int {
	return xxx_messageInfo_Secret.Size(m)
}
func (m *Secret) XXX_DiscardUnknown() {
	xxx_messageInfo_Secret.DiscardUnknown(m)
}

var xxx_messageInfo_Secret proto.InternalMessageInfo

func (m *Secret) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Secret) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type Secrets struct {
	Secrets              []*Secret `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Secrets) Reset()         { *m = Secrets{} }
func (m *Secrets) String() string { return proto.CompactTextString(m) }
func (*Secrets) ProtoMessage()    {}
func (*Secrets) Descriptor() ([]byte, []int) {
	return fileDescriptor_6acf428160d7a216, []int{15}
}

func (m *Secrets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Secrets.Unmarshal(m, b)
}
func (m *Secrets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Secrets.Marshal(b, m, deterministic)
}
func (m *Secrets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Secrets.Merge(m, src)
}
func (m *Secrets) XXX_Size() int {
	return xxx_messageInfo_Secrets.Size(m)
}
func (m *Secrets) XXX_DiscardUnknown() {
	xxx_messageInfo_Secrets.DiscardUnknown(m)
}

var xxx_messageInfo_Secrets proto.InternalMessageInfo

func (m *Secrets) GetSecrets() []*Secret {
	if m != nil {
		return m.Secrets
	}
	return nil
}

func init() {
	proto.RegisterType((*AddSecretValueRequest)(nil), "api.AddSecretValueRequest")
	proto.RegisterType((*AddSecretValueResponse)(nil), "api.AddSecretValueResponse")
	proto.RegisterType((*AddSecretBody)(nil), "api.AddSecretBody")
	proto.RegisterType((*SecretExistsRequest)(nil), "api.SecretExistsRequest")
	proto.RegisterType((*SecretExistsResponse)(nil), "api.SecretExistsResponse")
	proto.RegisterType((*UpdateSecretKeyValueRequest)(nil), "api.UpdateSecretKeyValueRequest")
	proto.RegisterType((*UpdateSecretKeyValueResponse)(nil), "api.UpdateSecretKeyValueResponse")
	proto.RegisterType((*DeleteSecretRequest)(nil), "api.DeleteSecretRequest")
	proto.RegisterType((*DeleteSecretKeyRequest)(nil), "api.DeleteSecretKeyRequest")
	proto.RegisterType((*DeleteSecretKeyResponse)(nil), "api.DeleteSecretKeyResponse")
	proto.RegisterType((*DeleteSecretResponse)(nil), "api.DeleteSecretResponse")
	proto.RegisterType((*GetSecretRequest)(nil), "api.GetSecretRequest")
	proto.RegisterType((*GetSecretsRequest)(nil), "api.GetSecretsRequest")
	proto.RegisterType((*CreateSecretRequest)(nil), "api.CreateSecretRequest")
	proto.RegisterType((*GetSecretRequest)(nil), "api.GetSecretRequest")
	proto.RegisterType((*Secret)(nil), "api.Secret")
	proto.RegisterMapType((map[string]string)(nil), "api.Secret.DataEntry")
	proto.RegisterType((*Secrets)(nil), "api.Secrets")
}

func init() { proto.RegisterFile("secret.proto", fileDescriptor_6acf428160d7a216) }

var fileDescriptor_6acf428160d7a216 = []byte{
	// 739 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x41, 0x4f, 0x13, 0x41,
	0x14, 0xce, 0xb6, 0x58, 0xe8, 0x6b, 0x89, 0xf0, 0x28, 0xb5, 0x6e, 0x1b, 0x53, 0x86, 0x98, 0x00,
	0x26, 0xbb, 0xb4, 0x20, 0x10, 0x82, 0x1a, 0x94, 0xc6, 0x03, 0xc6, 0x98, 0x12, 0x8d, 0x27, 0x93,
	0x81, 0x8e, 0xb8, 0x01, 0xba, 0x6b, 0x77, 0x4a, 0xdc, 0x34, 0x4d, 0x0c, 0xde, 0xbc, 0x78, 0x20,
	0xf1, 0xee, 0x6f, 0xf2, 0x2f, 0xf8, 0x43, 0xcc, 0xce, 0xcc, 0x6e, 0x77, 0xcb, 0x06, 0xa8, 0xa9,
	0xb7, 0x9d, 0xf7, 0x76, 0xde, 0xf7, 0xbd, 0x6f, 0x66, 0xbe, 0x07, 0x79, 0x97, 0x1d, 0x75, 0x18,
	0x37, 0x9c, 0x8e, 0xcd, 0x6d, 0x4c, 0x53, 0xc7, 0xd2, 0xcb, 0xc7, 0xb6, 0x7d, 0x7c, 0xca, 0x4c,
	0x11, 0x3a, 0xec, 0x7e, 0x34, 0xd9, 0x99, 0xc3, 0x3d, 0xf9, 0x87, 0x5e, 0x51, 0x49, 0xea, 0x58,
	0x26, 0x6d, 0xb7, 0x6d, 0x4e, 0xb9, 0x65, 0xb7, 0x5d, 0x99, 0x25, 0x3f, 0x34, 0x98, 0xdf, 0x6d,
	0xb5, 0x0e, 0x44, 0xcd, 0x77, 0xf4, 0xb4, 0xcb, 0x9a, 0xec, 0x73, 0x97, 0xb9, 0x1c, 0x2b, 0x90,
	0x6d, 0xd3, 0x33, 0xe6, 0x3a, 0xf4, 0x88, 0x95, 0xb4, 0xaa, 0xb6, 0x94, 0x6d, 0x0e, 0x02, 0xf8,
	0x00, 0x40, 0xf2, 0x78, 0x4d, 0xcf, 0x58, 0x29, 0x25, 0xd2, 0x91, 0x08, 0x6e, 0xc1, 0x34, 0x0d,
	0xca, 0x3e, 0xb7, 0x5b, 0x5e, 0x29, 0x5d, 0xd5, 0x96, 0x72, 0x75, 0x34, 0xa8, 0x63, 0x19, 0xbb,
	0xd1, 0x4c, 0x33, 0xfe, 0x23, 0x59, 0x87, 0xe2, 0x30, 0x21, 0xd7, 0xb1, 0xdb, 0x2e, 0x43, 0x1d,
	0xa6, 0xac, 0xb6, 0xcb, 0x3a, 0x9c, 0xb5, 0x04, 0xa1, 0xa9, 0x66, 0xb8, 0x26, 0x9b, 0x30, 0x1d,
	0xab, 0x8a, 0x33, 0x90, 0x3e, 0x61, 0x9e, 0x22, 0xee, 0x7f, 0x62, 0x01, 0xee, 0x9c, 0xfb, 0xf5,
	0x14, 0x5b, 0xb9, 0x20, 0x07, 0x30, 0x27, 0x77, 0x35, 0xbe, 0x58, 0x2e, 0x77, 0xc7, 0xd2, 0x3d,
	0x31, 0xa0, 0x10, 0x2f, 0xaa, 0x3a, 0x28, 0x42, 0x86, 0x89, 0x88, 0xe2, 0xaf, 0x56, 0xe4, 0x9b,
	0x06, 0xe5, 0xb7, 0x4e, 0x8b, 0x72, 0x26, 0xb7, 0xed, 0x33, 0x6f, 0x8c, 0x67, 0xa1, 0xa4, 0x48,
	0x27, 0x48, 0x31, 0x11, 0x95, 0x62, 0x0b, 0x2a, 0xc9, 0x24, 0x14, 0xfb, 0x12, 0x4c, 0x76, 0x45,
	0x3e, 0x90, 0x3f, 0x58, 0xfa, 0x22, 0xee, 0xb1, 0x53, 0x16, 0xec, 0x1c, 0x8f, 0x88, 0x9f, 0xa0,
	0x18, 0x2d, 0xba, 0xcf, 0xbc, 0xff, 0x24, 0x07, 0x59, 0x83, 0x7b, 0x57, 0x90, 0x06, 0x3d, 0xb7,
	0x44, 0x2a, 0xec, 0x59, 0x2d, 0xc9, 0x2a, 0x14, 0xe2, 0x3d, 0xdf, 0xb8, 0xe3, 0x0d, 0xcc, 0xbc,
	0x64, 0x7c, 0x9c, 0x12, 0xd5, 0x60, 0x36, 0xac, 0x78, 0xbb, 0xab, 0x4b, 0xde, 0xc3, 0xdc, 0x8b,
	0x0e, 0xa3, 0xa3, 0x1d, 0xd5, 0x22, 0x64, 0x24, 0xaa, 0xe0, 0x90, 0xab, 0xe7, 0xc4, 0x33, 0x56,
	0x15, 0x54, 0x8a, 0x7c, 0xd5, 0x20, 0x23, 0x43, 0x88, 0x30, 0xe1, 0x6f, 0x56, 0x85, 0xc4, 0x37,
	0x2e, 0xc3, 0x44, 0x8b, 0x72, 0x5a, 0x4a, 0x55, 0xd3, 0x4b, 0xb9, 0xfa, 0x7c, 0xa4, 0x82, 0xb1,
	0x47, 0x39, 0x6d, 0xb4, 0x79, 0xc7, 0x6b, 0x8a, 0x5f, 0xf4, 0x4d, 0xc8, 0x86, 0xa1, 0xdb, 0x3e,
	0xe4, 0xed, 0xd4, 0x96, 0x46, 0x56, 0x61, 0x52, 0x89, 0x81, 0x0f, 0x61, 0x52, 0xf2, 0xf2, 0xdf,
	0x5a, 0x7a, 0x98, 0x73, 0x90, 0xab, 0xff, 0x9c, 0x82, 0x69, 0x19, 0x3b, 0x60, 0x9d, 0x73, 0xeb,
	0x88, 0xa1, 0x0b, 0xf9, 0xa8, 0x40, 0x58, 0x12, 0xfb, 0x12, 0x34, 0xd3, 0x8b, 0x86, 0xb4, 0x56,
	0x23, 0xf0, 0x5d, 0xa3, 0xe1, 0xfb, 0x2e, 0xa9, 0x5d, 0xfc, 0xfe, 0x73, 0x99, 0x7a, 0x44, 0x16,
	0x7c, 0xcf, 0x75, 0xcd, 0xf3, 0xda, 0x21, 0xe3, 0xb4, 0x66, 0xf6, 0x42, 0x3d, 0xfb, 0xa6, 0x82,
	0xdf, 0x56, 0xda, 0xe1, 0x85, 0x06, 0xf9, 0xa8, 0x63, 0x28, 0xd4, 0x04, 0x67, 0xd2, 0xef, 0x27,
	0x64, 0xe4, 0xd5, 0x23, 0x4f, 0x04, 0xf0, 0x26, 0x3e, 0xbe, 0x11, 0xd8, 0xec, 0x0d, 0x6e, 0x51,
	0xdf, 0x94, 0x2e, 0x84, 0xc7, 0x90, 0x0d, 0x6f, 0x13, 0xca, 0x03, 0x1a, 0xbe, 0xaf, 0x7a, 0x54,
	0x45, 0xb2, 0x21, 0xf0, 0x56, 0xd1, 0x18, 0x0d, 0x0f, 0x3f, 0x40, 0xee, 0x95, 0xe5, 0x06, 0xf7,
	0x16, 0x8b, 0x71, 0xa8, 0xb0, 0xd3, 0x7c, 0x04, 0xcb, 0x25, 0xcb, 0x02, 0x6c, 0x11, 0x6f, 0x56,
	0x15, 0x7b, 0x90, 0x8f, 0x3e, 0x4d, 0x25, 0x66, 0x82, 0x43, 0x29, 0x31, 0x93, 0xde, 0x71, 0xd0,
	0xdc, 0xca, 0xa8, 0xcd, 0x7d, 0xd7, 0xe0, 0xee, 0x90, 0x9b, 0x60, 0xf9, 0x0a, 0xcc, 0xc0, 0xcd,
	0xf4, 0x4a, 0x72, 0x52, 0xd1, 0xd8, 0x11, 0x34, 0x36, 0x56, 0xd6, 0x47, 0x3c, 0xd3, 0xde, 0x09,
	0xf3, 0xfa, 0x78, 0xa9, 0xc1, 0x6c, 0x38, 0x17, 0x03, 0x43, 0x47, 0x3d, 0x3e, 0x85, 0xa3, 0xa3,
	0x46, 0x2f, 0x27, 0xe6, 0x14, 0x99, 0x86, 0x20, 0xf3, 0x8c, 0x8c, 0xa8, 0xc9, 0x76, 0x7c, 0xc4,
	0xe3, 0x2f, 0x0d, 0x0a, 0x49, 0x93, 0x06, 0xab, 0x02, 0xfc, 0x9a, 0x49, 0xa8, 0x2f, 0x5c, 0xf3,
	0x87, 0x22, 0xb9, 0x27, 0x48, 0x3e, 0xad, 0xef, 0xfc, 0x8b, 0x62, 0x66, 0x4f, 0xb8, 0x49, 0xff,
	0x30, 0x23, 0x1e, 0xf5, 0xda, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x48, 0x4d, 0x4a, 0x48, 0x6f,
	0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SecretServiceClient is the client API for SecretService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SecretServiceClient interface {
	CreateSecret(ctx context.Context, in *CreateSecretRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*Secret, error)
	ListSecrets(ctx context.Context, in *GetSecretsRequest, opts ...grpc.CallOption) (*Secrets, error)
	DeleteSecret(ctx context.Context, in *DeleteSecretRequest, opts ...grpc.CallOption) (*DeleteSecretResponse, error)
	DeleteSecretKey(ctx context.Context, in *DeleteSecretKeyRequest, opts ...grpc.CallOption) (*DeleteSecretKeyResponse, error)
	AddSecretKeyValue(ctx context.Context, in *AddSecretValueRequest, opts ...grpc.CallOption) (*AddSecretValueResponse, error)
	UpdateSecretKeyValue(ctx context.Context, in *UpdateSecretKeyValueRequest, opts ...grpc.CallOption) (*UpdateSecretKeyValueResponse, error)
}

type secretServiceClient struct {
	cc *grpc.ClientConn
}

func NewSecretServiceClient(cc *grpc.ClientConn) SecretServiceClient {
	return &secretServiceClient{cc}
}

func (c *secretServiceClient) CreateSecret(ctx context.Context, in *CreateSecretRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.SecretService/CreateSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretServiceClient) GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*Secret, error) {
	out := new(Secret)
	err := c.cc.Invoke(ctx, "/api.SecretService/GetSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretServiceClient) GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*Secret, error) {
	out := new(Secret)
	err := c.cc.Invoke(ctx, "/api.SecretService/GetSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretServiceClient) ListSecrets(ctx context.Context, in *GetSecretsRequest, opts ...grpc.CallOption) (*Secrets, error) {
	out := new(Secrets)
	err := c.cc.Invoke(ctx, "/api.SecretService/ListSecrets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretServiceClient) DeleteSecret(ctx context.Context, in *DeleteSecretRequest, opts ...grpc.CallOption) (*DeleteSecretResponse, error) {
	out := new(DeleteSecretResponse)
	err := c.cc.Invoke(ctx, "/api.SecretService/DeleteSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretServiceClient) DeleteSecretKey(ctx context.Context, in *DeleteSecretKeyRequest, opts ...grpc.CallOption) (*DeleteSecretKeyResponse, error) {
	out := new(DeleteSecretKeyResponse)
	err := c.cc.Invoke(ctx, "/api.SecretService/DeleteSecretKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretServiceClient) AddSecretKeyValue(ctx context.Context, in *AddSecretValueRequest, opts ...grpc.CallOption) (*AddSecretValueResponse, error) {
	out := new(AddSecretValueResponse)
	err := c.cc.Invoke(ctx, "/api.SecretService/AddSecretKeyValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretServiceClient) UpdateSecretKeyValue(ctx context.Context, in *UpdateSecretKeyValueRequest, opts ...grpc.CallOption) (*UpdateSecretKeyValueResponse, error) {
	out := new(UpdateSecretKeyValueResponse)
	err := c.cc.Invoke(ctx, "/api.SecretService/UpdateSecretKeyValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretServiceServer is the server API for SecretService service.
type SecretServiceServer interface {
	CreateSecret(context.Context, *CreateSecretRequest) (*empty.Empty, error)
	GetSecret(context.Context, *GetSecretRequest) (*Secret, error)
	ListSecrets(context.Context, *GetSecretsRequest) (*Secrets, error)
	DeleteSecret(context.Context, *DeleteSecretRequest) (*DeleteSecretResponse, error)
	DeleteSecretKey(context.Context, *DeleteSecretKeyRequest) (*DeleteSecretKeyResponse, error)
	AddSecretKeyValue(context.Context, *AddSecretValueRequest) (*AddSecretValueResponse, error)
	UpdateSecretKeyValue(context.Context, *UpdateSecretKeyValueRequest) (*UpdateSecretKeyValueResponse, error)
}

// UnimplementedSecretServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSecretServiceServer struct {
}

func (*UnimplementedSecretServiceServer) CreateSecret(ctx context.Context, req *CreateSecretRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSecret not implemented")
}
func (*UnimplementedSecretServiceServer) GetSecret(ctx context.Context, req *GetSecretRequest) (*Secret, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecret not implemented")
}
func (*UnimplementedSecretServiceServer) GetSecret(ctx context.Context, req *GetSecretRequest) (*Secret, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecret not implemented")
}
func (*UnimplementedSecretServiceServer) ListSecrets(ctx context.Context, req *GetSecretsRequest) (*Secrets, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSecrets not implemented")
}
func (*UnimplementedSecretServiceServer) DeleteSecret(ctx context.Context, req *DeleteSecretRequest) (*DeleteSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSecret not implemented")
}
func (*UnimplementedSecretServiceServer) DeleteSecretKey(ctx context.Context, req *DeleteSecretKeyRequest) (*DeleteSecretKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSecretKey not implemented")
}
func (*UnimplementedSecretServiceServer) AddSecretKeyValue(ctx context.Context, req *AddSecretValueRequest) (*AddSecretValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSecretKeyValue not implemented")
}
func (*UnimplementedSecretServiceServer) UpdateSecretKeyValue(ctx context.Context, req *UpdateSecretKeyValueRequest) (*UpdateSecretKeyValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSecretKeyValue not implemented")
}

func RegisterSecretServiceServer(s *grpc.Server, srv SecretServiceServer) {
	s.RegisterService(&_SecretService_serviceDesc, srv)
}

func _SecretService_CreateSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).CreateSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecretService/CreateSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).CreateSecret(ctx, req.(*CreateSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretService_GetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).GetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecretService/GetSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).GetSecret(ctx, req.(*GetSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretService_GetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).GetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecretService/GetSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).GetSecret(ctx, req.(*GetSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretService_ListSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).ListSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecretService/ListSecrets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).ListSecrets(ctx, req.(*GetSecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretService_DeleteSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).DeleteSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecretService/DeleteSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).DeleteSecret(ctx, req.(*DeleteSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretService_DeleteSecretKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSecretKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).DeleteSecretKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecretService/DeleteSecretKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).DeleteSecretKey(ctx, req.(*DeleteSecretKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretService_AddSecretKeyValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSecretValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).AddSecretKeyValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecretService/AddSecretKeyValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).AddSecretKeyValue(ctx, req.(*AddSecretValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretService_UpdateSecretKeyValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSecretKeyValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).UpdateSecretKeyValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecretService/UpdateSecretKeyValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).UpdateSecretKeyValue(ctx, req.(*UpdateSecretKeyValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SecretService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.SecretService",
	HandlerType: (*SecretServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSecret",
			Handler:    _SecretService_CreateSecret_Handler,
		},
		{
			MethodName: "GetSecret",
			Handler:    _SecretService_GetSecret_Handler,
		},
		{
			MethodName: "GetSecret",
			Handler:    _SecretService_GetSecret_Handler,
		},
		{
			MethodName: "ListSecrets",
			Handler:    _SecretService_ListSecrets_Handler,
		},
		{
			MethodName: "DeleteSecret",
			Handler:    _SecretService_DeleteSecret_Handler,
		},
		{
			MethodName: "DeleteSecretKey",
			Handler:    _SecretService_DeleteSecretKey_Handler,
		},
		{
			MethodName: "AddSecretKeyValue",
			Handler:    _SecretService_AddSecretKeyValue_Handler,
		},
		{
			MethodName: "UpdateSecretKeyValue",
			Handler:    _SecretService_UpdateSecretKeyValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "secret.proto",
}
