// Code generated by protoc-gen-go. DO NOT EDIT.
// source: secret.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SecretExistsRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SecretName           string   `protobuf:"bytes,2,opt,name=secretName,proto3" json:"secretName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecretExistsRequest) Reset()         { *m = SecretExistsRequest{} }
func (m *SecretExistsRequest) String() string { return proto.CompactTextString(m) }
func (*SecretExistsRequest) ProtoMessage()    {}
func (*SecretExistsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6acf428160d7a216, []int{0}
}

func (m *SecretExistsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretExistsRequest.Unmarshal(m, b)
}
func (m *SecretExistsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretExistsRequest.Marshal(b, m, deterministic)
}
func (m *SecretExistsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretExistsRequest.Merge(m, src)
}
func (m *SecretExistsRequest) XXX_Size() int {
	return xxx_messageInfo_SecretExistsRequest.Size(m)
}
func (m *SecretExistsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretExistsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SecretExistsRequest proto.InternalMessageInfo

func (m *SecretExistsRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *SecretExistsRequest) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

type SecretExistsResponse struct {
	Exists               bool     `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecretExistsResponse) Reset()         { *m = SecretExistsResponse{} }
func (m *SecretExistsResponse) String() string { return proto.CompactTextString(m) }
func (*SecretExistsResponse) ProtoMessage()    {}
func (*SecretExistsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6acf428160d7a216, []int{1}
}

func (m *SecretExistsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretExistsResponse.Unmarshal(m, b)
}
func (m *SecretExistsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretExistsResponse.Marshal(b, m, deterministic)
}
func (m *SecretExistsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretExistsResponse.Merge(m, src)
}
func (m *SecretExistsResponse) XXX_Size() int {
	return xxx_messageInfo_SecretExistsResponse.Size(m)
}
func (m *SecretExistsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretExistsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SecretExistsResponse proto.InternalMessageInfo

func (m *SecretExistsResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

type GetSecretRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SecretName           string   `protobuf:"bytes,2,opt,name=secretName,proto3" json:"secretName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSecretRequest) Reset()         { *m = GetSecretRequest{} }
func (m *GetSecretRequest) String() string { return proto.CompactTextString(m) }
func (*GetSecretRequest) ProtoMessage()    {}
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6acf428160d7a216, []int{2}
}

func (m *GetSecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSecretRequest.Unmarshal(m, b)
}
func (m *GetSecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSecretRequest.Marshal(b, m, deterministic)
}
func (m *GetSecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSecretRequest.Merge(m, src)
}
func (m *GetSecretRequest) XXX_Size() int {
	return xxx_messageInfo_GetSecretRequest.Size(m)
}
func (m *GetSecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSecretRequest proto.InternalMessageInfo

func (m *GetSecretRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetSecretRequest) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

type CreateSecretRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Secret               *Secret  `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSecretRequest) Reset()         { *m = CreateSecretRequest{} }
func (m *CreateSecretRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSecretRequest) ProtoMessage()    {}
func (*CreateSecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6acf428160d7a216, []int{3}
}

func (m *CreateSecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSecretRequest.Unmarshal(m, b)
}
func (m *CreateSecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSecretRequest.Marshal(b, m, deterministic)
}
func (m *CreateSecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSecretRequest.Merge(m, src)
}
func (m *CreateSecretRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSecretRequest.Size(m)
}
func (m *CreateSecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSecretRequest proto.InternalMessageInfo

func (m *CreateSecretRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *CreateSecretRequest) GetSecret() *Secret {
	if m != nil {
		return m.Secret
	}
	return nil
}

type GetSecretRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSecretRequest) Reset()         { *m = GetSecretRequest{} }
func (m *GetSecretRequest) String() string { return proto.CompactTextString(m) }
func (*GetSecretRequest) ProtoMessage()    {}
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6acf428160d7a216, []int{1}
}

func (m *GetSecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSecretRequest.Unmarshal(m, b)
}
func (m *GetSecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSecretRequest.Marshal(b, m, deterministic)
}
func (m *GetSecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSecretRequest.Merge(m, src)
}
func (m *GetSecretRequest) XXX_Size() int {
	return xxx_messageInfo_GetSecretRequest.Size(m)
}
func (m *GetSecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSecretRequest proto.InternalMessageInfo

func (m *GetSecretRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetSecretRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Secret struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data                 map[string]string `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Secret) Reset()         { *m = Secret{} }
func (m *Secret) String() string { return proto.CompactTextString(m) }
func (*Secret) ProtoMessage()    {}
func (*Secret) Descriptor() ([]byte, []int) {
	return fileDescriptor_6acf428160d7a216, []int{2}
}

func (m *Secret) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Secret.Unmarshal(m, b)
}
func (m *Secret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Secret.Marshal(b, m, deterministic)
}
func (m *Secret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Secret.Merge(m, src)
}
func (m *Secret) XXX_Size() int {
	return xxx_messageInfo_Secret.Size(m)
}
func (m *Secret) XXX_DiscardUnknown() {
	xxx_messageInfo_Secret.DiscardUnknown(m)
}

var xxx_messageInfo_Secret proto.InternalMessageInfo

func (m *Secret) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Secret) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*SecretExistsRequest)(nil), "api.SecretExistsRequest")
	proto.RegisterType((*SecretExistsResponse)(nil), "api.SecretExistsResponse")
	proto.RegisterType((*GetSecretRequest)(nil), "api.GetSecretRequest")
	proto.RegisterType((*CreateSecretRequest)(nil), "api.CreateSecretRequest")
	proto.RegisterType((*GetSecretRequest)(nil), "api.GetSecretRequest")
	proto.RegisterType((*Secret)(nil), "api.Secret")
	proto.RegisterMapType((map[string]string)(nil), "api.Secret.DataEntry")
}

func init() { proto.RegisterFile("secret.proto", fileDescriptor_6acf428160d7a216) }

var fileDescriptor_6acf428160d7a216 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0x99, 0xb4, 0x5f, 0x21, 0xb7, 0xfd, 0xa0, 0x8c, 0x7f, 0x08, 0xb1, 0x8b, 0x1a, 0x37,
	0x51, 0x61, 0x62, 0xeb, 0x42, 0xe9, 0xd6, 0x16, 0xf7, 0xe9, 0xc6, 0xed, 0x6d, 0xbd, 0x96, 0x60,
	0x9b, 0xc4, 0xcc, 0xb4, 0x50, 0xa4, 0x20, 0xbe, 0x82, 0x8f, 0xe6, 0x2b, 0x08, 0xbe, 0x86, 0x64,
	0x26, 0x4d, 0x83, 0x08, 0xe2, 0x6e, 0xe6, 0x9e, 0xe1, 0x9c, 0x3b, 0xbf, 0x03, 0x2d, 0x49, 0xd3,
	0x8c, 0x94, 0x48, 0xb3, 0x44, 0x25, 0xbc, 0x86, 0x69, 0xe4, 0x1e, 0xcd, 0x92, 0x64, 0x36, 0xa7,
	0x40, 0x8f, 0x26, 0xcb, 0x87, 0x80, 0x16, 0xa9, 0x5a, 0x9b, 0x17, 0x6e, 0xa7, 0x10, 0x31, 0x8d,
	0x02, 0x8c, 0xe3, 0x44, 0xa1, 0x8a, 0x92, 0x58, 0x1a, 0xd5, 0xbb, 0x83, 0xbd, 0x9b, 0x8c, 0x50,
	0xd1, 0x58, 0xbb, 0x86, 0xf4, 0xb4, 0x24, 0xa9, 0x78, 0x07, 0xec, 0x18, 0x17, 0x24, 0x53, 0x9c,
	0x92, 0xc3, 0xba, 0xcc, 0xb7, 0xc3, 0xdd, 0x80, 0x9f, 0x40, 0xc3, 0x2c, 0xe1, 0x58, 0x5d, 0xe6,
	0x37, 0xfb, 0x4d, 0x81, 0x69, 0x24, 0x0a, 0x87, 0x42, 0xf2, 0x86, 0xd0, 0xbe, 0x25, 0xf5, 0x17,
	0x5b, 0x0e, 0xf5, 0xfc, 0xa2, 0x4d, 0xed, 0x50, 0x9f, 0xbd, 0x17, 0x06, 0x0d, 0xe3, 0x51, 0xca,
	0x6c, 0x27, 0xf3, 0x53, 0xa8, 0xdf, 0xa3, 0x42, 0xc7, 0xea, 0xd6, 0xfc, 0x66, 0xff, 0xa0, 0xb2,
	0x87, 0x18, 0xa2, 0xc2, 0x51, 0xac, 0xb2, 0x75, 0xa8, 0x9f, 0xb8, 0x57, 0x60, 0x97, 0x23, 0xde,
	0x86, 0xda, 0x23, 0xad, 0x0b, 0xab, 0xfc, 0xc8, 0xf7, 0xe1, 0xdf, 0x0a, 0xe7, 0xcb, 0x6d, 0xba,
	0xb9, 0x0c, 0xac, 0x6b, 0xd6, 0xff, 0x64, 0xf0, 0xdf, 0x78, 0x8e, 0x29, 0x5b, 0x45, 0x53, 0xe2,
	0x12, 0x5a, 0x55, 0x68, 0xdc, 0xd1, 0xb9, 0x3f, 0x70, 0x74, 0x0f, 0x85, 0xa1, 0x2f, 0xb6, 0xd5,
	0x88, 0x51, 0x5e, 0x8d, 0xd7, 0x7b, 0x7d, 0xff, 0x78, 0xb3, 0xce, 0xbd, 0xe3, 0xbc, 0x16, 0x19,
	0xac, 0x7a, 0x13, 0x52, 0xd8, 0x0b, 0x9e, 0x4b, 0x18, 0x9b, 0xc0, 0x60, 0x94, 0x83, 0x82, 0x27,
	0x47, 0xb0, 0x4b, 0x9e, 0xdc, 0xfc, 0xf4, 0x3b, 0x5f, 0xb7, 0x5a, 0x84, 0x77, 0xa1, 0x33, 0xce,
	0xb8, 0xff, 0x6b, 0x86, 0x99, 0x6d, 0x26, 0x0d, 0xbd, 0xe5, 0xe5, 0x57, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xd1, 0x1d, 0xb1, 0x09, 0x63, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SecretServiceClient is the client API for SecretService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SecretServiceClient interface {
	CreateSecret(ctx context.Context, in *CreateSecretRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*Secret, error)
}

type secretServiceClient struct {
	cc *grpc.ClientConn
}

func NewSecretServiceClient(cc *grpc.ClientConn) SecretServiceClient {
	return &secretServiceClient{cc}
}

func (c *secretServiceClient) CreateSecret(ctx context.Context, in *CreateSecretRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.SecretService/CreateSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretServiceClient) GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*Secret, error) {
	out := new(Secret)
	err := c.cc.Invoke(ctx, "/api.SecretService/GetSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretServiceClient) GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*Secret, error) {
	out := new(Secret)
	err := c.cc.Invoke(ctx, "/api.SecretService/GetSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretServiceServer is the server API for SecretService service.
type SecretServiceServer interface {
	CreateSecret(context.Context, *CreateSecretRequest) (*empty.Empty, error)
	GetSecret(context.Context, *GetSecretRequest) (*Secret, error)
}

// UnimplementedSecretServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSecretServiceServer struct {
}

func (*UnimplementedSecretServiceServer) CreateSecret(ctx context.Context, req *CreateSecretRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSecret not implemented")
}
func (*UnimplementedSecretServiceServer) GetSecret(ctx context.Context, req *GetSecretRequest) (*Secret, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecret not implemented")
}
func (*UnimplementedSecretServiceServer) GetSecret(ctx context.Context, req *GetSecretRequest) (*Secret, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecret not implemented")
}

func RegisterSecretServiceServer(s *grpc.Server, srv SecretServiceServer) {
	s.RegisterService(&_SecretService_serviceDesc, srv)
}

func _SecretService_CreateSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).CreateSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecretService/CreateSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).CreateSecret(ctx, req.(*CreateSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretService_GetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).GetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecretService/GetSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).GetSecret(ctx, req.(*GetSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretService_GetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).GetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecretService/GetSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).GetSecret(ctx, req.(*GetSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SecretService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.SecretService",
	HandlerType: (*SecretServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSecret",
			Handler:    _SecretService_CreateSecret_Handler,
		},
		{
			MethodName: "GetSecret",
			Handler:    _SecretService_GetSecret_Handler,
		},
		{
			MethodName: "GetSecret",
			Handler:    _SecretService_GetSecret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "secret.proto",
}
