// Code generated by protoc-gen-go. DO NOT EDIT.
// source: workflow.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateWorkflowExecutionRequest struct {
	Namespace            string             `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	WorkflowExecution    *WorkflowExecution `protobuf:"bytes,2,opt,name=workflowExecution,proto3" json:"workflowExecution,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreateWorkflowExecutionRequest) Reset()         { *m = CreateWorkflowExecutionRequest{} }
func (m *CreateWorkflowExecutionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateWorkflowExecutionRequest) ProtoMessage()    {}
func (*CreateWorkflowExecutionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{0}
}

func (m *CreateWorkflowExecutionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWorkflowExecutionRequest.Unmarshal(m, b)
}
func (m *CreateWorkflowExecutionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWorkflowExecutionRequest.Marshal(b, m, deterministic)
}
func (m *CreateWorkflowExecutionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWorkflowExecutionRequest.Merge(m, src)
}
func (m *CreateWorkflowExecutionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateWorkflowExecutionRequest.Size(m)
}
func (m *CreateWorkflowExecutionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWorkflowExecutionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWorkflowExecutionRequest proto.InternalMessageInfo

func (m *CreateWorkflowExecutionRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *CreateWorkflowExecutionRequest) GetWorkflowExecution() *WorkflowExecution {
	if m != nil {
		return m.WorkflowExecution
	}
	return nil
}

type GetWorkflowExecutionRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWorkflowExecutionRequest) Reset()         { *m = GetWorkflowExecutionRequest{} }
func (m *GetWorkflowExecutionRequest) String() string { return proto.CompactTextString(m) }
func (*GetWorkflowExecutionRequest) ProtoMessage()    {}
func (*GetWorkflowExecutionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{1}
}

func (m *GetWorkflowExecutionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWorkflowExecutionRequest.Unmarshal(m, b)
}
func (m *GetWorkflowExecutionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWorkflowExecutionRequest.Marshal(b, m, deterministic)
}
func (m *GetWorkflowExecutionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWorkflowExecutionRequest.Merge(m, src)
}
func (m *GetWorkflowExecutionRequest) XXX_Size() int {
	return xxx_messageInfo_GetWorkflowExecutionRequest.Size(m)
}
func (m *GetWorkflowExecutionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWorkflowExecutionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWorkflowExecutionRequest proto.InternalMessageInfo

func (m *GetWorkflowExecutionRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetWorkflowExecutionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetArtifactRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArtifactRequest) Reset()         { *m = GetArtifactRequest{} }
func (m *GetArtifactRequest) String() string { return proto.CompactTextString(m) }
func (*GetArtifactRequest) ProtoMessage()    {}
func (*GetArtifactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{2}
}

func (m *GetArtifactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArtifactRequest.Unmarshal(m, b)
}
func (m *GetArtifactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArtifactRequest.Marshal(b, m, deterministic)
}
func (m *GetArtifactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArtifactRequest.Merge(m, src)
}
func (m *GetArtifactRequest) XXX_Size() int {
	return xxx_messageInfo_GetArtifactRequest.Size(m)
}
func (m *GetArtifactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArtifactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetArtifactRequest proto.InternalMessageInfo

func (m *GetArtifactRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetArtifactRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetArtifactRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type WatchWorkflowExecutionRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WatchWorkflowExecutionRequest) Reset()         { *m = WatchWorkflowExecutionRequest{} }
func (m *WatchWorkflowExecutionRequest) String() string { return proto.CompactTextString(m) }
func (*WatchWorkflowExecutionRequest) ProtoMessage()    {}
func (*WatchWorkflowExecutionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{3}
}

func (m *WatchWorkflowExecutionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchWorkflowExecutionRequest.Unmarshal(m, b)
}
func (m *WatchWorkflowExecutionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchWorkflowExecutionRequest.Marshal(b, m, deterministic)
}
func (m *WatchWorkflowExecutionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchWorkflowExecutionRequest.Merge(m, src)
}
func (m *WatchWorkflowExecutionRequest) XXX_Size() int {
	return xxx_messageInfo_WatchWorkflowExecutionRequest.Size(m)
}
func (m *WatchWorkflowExecutionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchWorkflowExecutionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WatchWorkflowExecutionRequest proto.InternalMessageInfo

func (m *WatchWorkflowExecutionRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *WatchWorkflowExecutionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ResubmitWorkflowExecutionRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResubmitWorkflowExecutionRequest) Reset()         { *m = ResubmitWorkflowExecutionRequest{} }
func (m *ResubmitWorkflowExecutionRequest) String() string { return proto.CompactTextString(m) }
func (*ResubmitWorkflowExecutionRequest) ProtoMessage()    {}
func (*ResubmitWorkflowExecutionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{4}
}

func (m *ResubmitWorkflowExecutionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResubmitWorkflowExecutionRequest.Unmarshal(m, b)
}
func (m *ResubmitWorkflowExecutionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResubmitWorkflowExecutionRequest.Marshal(b, m, deterministic)
}
func (m *ResubmitWorkflowExecutionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResubmitWorkflowExecutionRequest.Merge(m, src)
}
func (m *ResubmitWorkflowExecutionRequest) XXX_Size() int {
	return xxx_messageInfo_ResubmitWorkflowExecutionRequest.Size(m)
}
func (m *ResubmitWorkflowExecutionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResubmitWorkflowExecutionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResubmitWorkflowExecutionRequest proto.InternalMessageInfo

func (m *ResubmitWorkflowExecutionRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ResubmitWorkflowExecutionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TerminateWorkflowExecutionRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TerminateWorkflowExecutionRequest) Reset()         { *m = TerminateWorkflowExecutionRequest{} }
func (m *TerminateWorkflowExecutionRequest) String() string { return proto.CompactTextString(m) }
func (*TerminateWorkflowExecutionRequest) ProtoMessage()    {}
func (*TerminateWorkflowExecutionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{5}
}

func (m *TerminateWorkflowExecutionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TerminateWorkflowExecutionRequest.Unmarshal(m, b)
}
func (m *TerminateWorkflowExecutionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TerminateWorkflowExecutionRequest.Marshal(b, m, deterministic)
}
func (m *TerminateWorkflowExecutionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TerminateWorkflowExecutionRequest.Merge(m, src)
}
func (m *TerminateWorkflowExecutionRequest) XXX_Size() int {
	return xxx_messageInfo_TerminateWorkflowExecutionRequest.Size(m)
}
func (m *TerminateWorkflowExecutionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TerminateWorkflowExecutionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TerminateWorkflowExecutionRequest proto.InternalMessageInfo

func (m *TerminateWorkflowExecutionRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *TerminateWorkflowExecutionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetWorkflowExecutionLogsRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PodName              string   `protobuf:"bytes,3,opt,name=podName,proto3" json:"podName,omitempty"`
	ContainerName        string   `protobuf:"bytes,4,opt,name=containerName,proto3" json:"containerName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWorkflowExecutionLogsRequest) Reset()         { *m = GetWorkflowExecutionLogsRequest{} }
func (m *GetWorkflowExecutionLogsRequest) String() string { return proto.CompactTextString(m) }
func (*GetWorkflowExecutionLogsRequest) ProtoMessage()    {}
func (*GetWorkflowExecutionLogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{6}
}

func (m *GetWorkflowExecutionLogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWorkflowExecutionLogsRequest.Unmarshal(m, b)
}
func (m *GetWorkflowExecutionLogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWorkflowExecutionLogsRequest.Marshal(b, m, deterministic)
}
func (m *GetWorkflowExecutionLogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWorkflowExecutionLogsRequest.Merge(m, src)
}
func (m *GetWorkflowExecutionLogsRequest) XXX_Size() int {
	return xxx_messageInfo_GetWorkflowExecutionLogsRequest.Size(m)
}
func (m *GetWorkflowExecutionLogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWorkflowExecutionLogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWorkflowExecutionLogsRequest proto.InternalMessageInfo

func (m *GetWorkflowExecutionLogsRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetWorkflowExecutionLogsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetWorkflowExecutionLogsRequest) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *GetWorkflowExecutionLogsRequest) GetContainerName() string {
	if m != nil {
		return m.ContainerName
	}
	return ""
}

type GetWorkflowExecutionMetricsRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PodName              string   `protobuf:"bytes,3,opt,name=podName,proto3" json:"podName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWorkflowExecutionMetricsRequest) Reset()         { *m = GetWorkflowExecutionMetricsRequest{} }
func (m *GetWorkflowExecutionMetricsRequest) String() string { return proto.CompactTextString(m) }
func (*GetWorkflowExecutionMetricsRequest) ProtoMessage()    {}
func (*GetWorkflowExecutionMetricsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{7}
}

func (m *GetWorkflowExecutionMetricsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWorkflowExecutionMetricsRequest.Unmarshal(m, b)
}
func (m *GetWorkflowExecutionMetricsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWorkflowExecutionMetricsRequest.Marshal(b, m, deterministic)
}
func (m *GetWorkflowExecutionMetricsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWorkflowExecutionMetricsRequest.Merge(m, src)
}
func (m *GetWorkflowExecutionMetricsRequest) XXX_Size() int {
	return xxx_messageInfo_GetWorkflowExecutionMetricsRequest.Size(m)
}
func (m *GetWorkflowExecutionMetricsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWorkflowExecutionMetricsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWorkflowExecutionMetricsRequest proto.InternalMessageInfo

func (m *GetWorkflowExecutionMetricsRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetWorkflowExecutionMetricsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetWorkflowExecutionMetricsRequest) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

type GetWorkflowExecutionMetricsResponse struct {
	Metrics              []*Metric `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetWorkflowExecutionMetricsResponse) Reset()         { *m = GetWorkflowExecutionMetricsResponse{} }
func (m *GetWorkflowExecutionMetricsResponse) String() string { return proto.CompactTextString(m) }
func (*GetWorkflowExecutionMetricsResponse) ProtoMessage()    {}
func (*GetWorkflowExecutionMetricsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{8}
}

func (m *GetWorkflowExecutionMetricsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWorkflowExecutionMetricsResponse.Unmarshal(m, b)
}
func (m *GetWorkflowExecutionMetricsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWorkflowExecutionMetricsResponse.Marshal(b, m, deterministic)
}
func (m *GetWorkflowExecutionMetricsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWorkflowExecutionMetricsResponse.Merge(m, src)
}
func (m *GetWorkflowExecutionMetricsResponse) XXX_Size() int {
	return xxx_messageInfo_GetWorkflowExecutionMetricsResponse.Size(m)
}
func (m *GetWorkflowExecutionMetricsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWorkflowExecutionMetricsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWorkflowExecutionMetricsResponse proto.InternalMessageInfo

func (m *GetWorkflowExecutionMetricsResponse) GetMetrics() []*Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type ListWorkflowExecutionsRequest struct {
	Namespace               string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	WorkflowTemplateUid     string   `protobuf:"bytes,2,opt,name=workflowTemplateUid,proto3" json:"workflowTemplateUid,omitempty"`
	WorkflowTemplateVersion string   `protobuf:"bytes,3,opt,name=workflowTemplateVersion,proto3" json:"workflowTemplateVersion,omitempty"`
	PageSize                int32    `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Page                    int32    `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *ListWorkflowExecutionsRequest) Reset()         { *m = ListWorkflowExecutionsRequest{} }
func (m *ListWorkflowExecutionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListWorkflowExecutionsRequest) ProtoMessage()    {}
func (*ListWorkflowExecutionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{9}
}

func (m *ListWorkflowExecutionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListWorkflowExecutionsRequest.Unmarshal(m, b)
}
func (m *ListWorkflowExecutionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListWorkflowExecutionsRequest.Marshal(b, m, deterministic)
}
func (m *ListWorkflowExecutionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListWorkflowExecutionsRequest.Merge(m, src)
}
func (m *ListWorkflowExecutionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListWorkflowExecutionsRequest.Size(m)
}
func (m *ListWorkflowExecutionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListWorkflowExecutionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListWorkflowExecutionsRequest proto.InternalMessageInfo

func (m *ListWorkflowExecutionsRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ListWorkflowExecutionsRequest) GetWorkflowTemplateUid() string {
	if m != nil {
		return m.WorkflowTemplateUid
	}
	return ""
}

func (m *ListWorkflowExecutionsRequest) GetWorkflowTemplateVersion() string {
	if m != nil {
		return m.WorkflowTemplateVersion
	}
	return ""
}

func (m *ListWorkflowExecutionsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListWorkflowExecutionsRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type ListWorkflowExecutionsResponse struct {
	Count                int32                `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	WorkflowExecutions   []*WorkflowExecution `protobuf:"bytes,2,rep,name=workflowExecutions,proto3" json:"workflowExecutions,omitempty"`
	Page                 int32                `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Pages                int32                `protobuf:"varint,4,opt,name=pages,proto3" json:"pages,omitempty"`
	TotalCount           int32                `protobuf:"varint,5,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListWorkflowExecutionsResponse) Reset()         { *m = ListWorkflowExecutionsResponse{} }
func (m *ListWorkflowExecutionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListWorkflowExecutionsResponse) ProtoMessage()    {}
func (*ListWorkflowExecutionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{10}
}

func (m *ListWorkflowExecutionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListWorkflowExecutionsResponse.Unmarshal(m, b)
}
func (m *ListWorkflowExecutionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListWorkflowExecutionsResponse.Marshal(b, m, deterministic)
}
func (m *ListWorkflowExecutionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListWorkflowExecutionsResponse.Merge(m, src)
}
func (m *ListWorkflowExecutionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListWorkflowExecutionsResponse.Size(m)
}
func (m *ListWorkflowExecutionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListWorkflowExecutionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListWorkflowExecutionsResponse proto.InternalMessageInfo

func (m *ListWorkflowExecutionsResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ListWorkflowExecutionsResponse) GetWorkflowExecutions() []*WorkflowExecution {
	if m != nil {
		return m.WorkflowExecutions
	}
	return nil
}

func (m *ListWorkflowExecutionsResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListWorkflowExecutionsResponse) GetPages() int32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *ListWorkflowExecutionsResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type LogEntry struct {
	Timestamp            string   `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogEntry) Reset()         { *m = LogEntry{} }
func (m *LogEntry) String() string { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()    {}
func (*LogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{11}
}

func (m *LogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEntry.Unmarshal(m, b)
}
func (m *LogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEntry.Marshal(b, m, deterministic)
}
func (m *LogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEntry.Merge(m, src)
}
func (m *LogEntry) XXX_Size() int {
	return xxx_messageInfo_LogEntry.Size(m)
}
func (m *LogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LogEntry proto.InternalMessageInfo

func (m *LogEntry) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *LogEntry) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type WorkflowExecution struct {
	CreatedAt            string                        `protobuf:"bytes,1,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Uid                  string                        `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string                        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Phase                string                        `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	StartedAt            string                        `protobuf:"bytes,5,opt,name=startedAt,proto3" json:"startedAt,omitempty"`
	FinishedAt           string                        `protobuf:"bytes,6,opt,name=finishedAt,proto3" json:"finishedAt,omitempty"`
	Manifest             string                        `protobuf:"bytes,7,opt,name=manifest,proto3" json:"manifest,omitempty"`
	Parameters           []*WorkflowExecutionParameter `protobuf:"bytes,8,rep,name=parameters,proto3" json:"parameters,omitempty"`
	WorkflowTemplate     *WorkflowTemplate             `protobuf:"bytes,9,opt,name=workflowTemplate,proto3" json:"workflowTemplate,omitempty"`
	Labels               []*KeyValue                   `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *WorkflowExecution) Reset()         { *m = WorkflowExecution{} }
func (m *WorkflowExecution) String() string { return proto.CompactTextString(m) }
func (*WorkflowExecution) ProtoMessage()    {}
func (*WorkflowExecution) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{12}
}

func (m *WorkflowExecution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowExecution.Unmarshal(m, b)
}
func (m *WorkflowExecution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowExecution.Marshal(b, m, deterministic)
}
func (m *WorkflowExecution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowExecution.Merge(m, src)
}
func (m *WorkflowExecution) XXX_Size() int {
	return xxx_messageInfo_WorkflowExecution.Size(m)
}
func (m *WorkflowExecution) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowExecution.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowExecution proto.InternalMessageInfo

func (m *WorkflowExecution) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *WorkflowExecution) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *WorkflowExecution) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WorkflowExecution) GetPhase() string {
	if m != nil {
		return m.Phase
	}
	return ""
}

func (m *WorkflowExecution) GetStartedAt() string {
	if m != nil {
		return m.StartedAt
	}
	return ""
}

func (m *WorkflowExecution) GetFinishedAt() string {
	if m != nil {
		return m.FinishedAt
	}
	return ""
}

func (m *WorkflowExecution) GetManifest() string {
	if m != nil {
		return m.Manifest
	}
	return ""
}

func (m *WorkflowExecution) GetParameters() []*WorkflowExecutionParameter {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *WorkflowExecution) GetWorkflowTemplate() *WorkflowTemplate {
	if m != nil {
		return m.WorkflowTemplate
	}
	return nil
}

func (m *WorkflowExecution) GetLabels() []*KeyValue {
	if m != nil {
		return m.Labels
	}
	return nil
}

type WorkflowExecutionParameter struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkflowExecutionParameter) Reset()         { *m = WorkflowExecutionParameter{} }
func (m *WorkflowExecutionParameter) String() string { return proto.CompactTextString(m) }
func (*WorkflowExecutionParameter) ProtoMessage()    {}
func (*WorkflowExecutionParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{13}
}

func (m *WorkflowExecutionParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowExecutionParameter.Unmarshal(m, b)
}
func (m *WorkflowExecutionParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowExecutionParameter.Marshal(b, m, deterministic)
}
func (m *WorkflowExecutionParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowExecutionParameter.Merge(m, src)
}
func (m *WorkflowExecutionParameter) XXX_Size() int {
	return xxx_messageInfo_WorkflowExecutionParameter.Size(m)
}
func (m *WorkflowExecutionParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowExecutionParameter.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowExecutionParameter proto.InternalMessageInfo

func (m *WorkflowExecutionParameter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WorkflowExecutionParameter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ArtifactResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArtifactResponse) Reset()         { *m = ArtifactResponse{} }
func (m *ArtifactResponse) String() string { return proto.CompactTextString(m) }
func (*ArtifactResponse) ProtoMessage()    {}
func (*ArtifactResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{14}
}

func (m *ArtifactResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArtifactResponse.Unmarshal(m, b)
}
func (m *ArtifactResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArtifactResponse.Marshal(b, m, deterministic)
}
func (m *ArtifactResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArtifactResponse.Merge(m, src)
}
func (m *ArtifactResponse) XXX_Size() int {
	return xxx_messageInfo_ArtifactResponse.Size(m)
}
func (m *ArtifactResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ArtifactResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ArtifactResponse proto.InternalMessageInfo

func (m *ArtifactResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type File struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Extension            string   `protobuf:"bytes,3,opt,name=extension,proto3" json:"extension,omitempty"`
	Size                 int64    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	ContentType          string   `protobuf:"bytes,5,opt,name=contentType,proto3" json:"contentType,omitempty"`
	LastModified         string   `protobuf:"bytes,6,opt,name=lastModified,proto3" json:"lastModified,omitempty"`
	Directory            bool     `protobuf:"varint,7,opt,name=directory,proto3" json:"directory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{15}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetExtension() string {
	if m != nil {
		return m.Extension
	}
	return ""
}

func (m *File) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *File) GetLastModified() string {
	if m != nil {
		return m.LastModified
	}
	return ""
}

func (m *File) GetDirectory() bool {
	if m != nil {
		return m.Directory
	}
	return false
}

type ListFilesRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFilesRequest) Reset()         { *m = ListFilesRequest{} }
func (m *ListFilesRequest) String() string { return proto.CompactTextString(m) }
func (*ListFilesRequest) ProtoMessage()    {}
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{16}
}

func (m *ListFilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFilesRequest.Unmarshal(m, b)
}
func (m *ListFilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFilesRequest.Marshal(b, m, deterministic)
}
func (m *ListFilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFilesRequest.Merge(m, src)
}
func (m *ListFilesRequest) XXX_Size() int {
	return xxx_messageInfo_ListFilesRequest.Size(m)
}
func (m *ListFilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListFilesRequest proto.InternalMessageInfo

func (m *ListFilesRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ListFilesRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListFilesRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ListFilesResponse struct {
	Files                []*File  `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	ParentPath           string   `protobuf:"bytes,2,opt,name=parentPath,proto3" json:"parentPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFilesResponse) Reset()         { *m = ListFilesResponse{} }
func (m *ListFilesResponse) String() string { return proto.CompactTextString(m) }
func (*ListFilesResponse) ProtoMessage()    {}
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{17}
}

func (m *ListFilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFilesResponse.Unmarshal(m, b)
}
func (m *ListFilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFilesResponse.Marshal(b, m, deterministic)
}
func (m *ListFilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFilesResponse.Merge(m, src)
}
func (m *ListFilesResponse) XXX_Size() int {
	return xxx_messageInfo_ListFilesResponse.Size(m)
}
func (m *ListFilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListFilesResponse proto.InternalMessageInfo

func (m *ListFilesResponse) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *ListFilesResponse) GetParentPath() string {
	if m != nil {
		return m.ParentPath
	}
	return ""
}

type Statistics struct {
	WorkflowStatus       string   `protobuf:"bytes,1,opt,name=workflowStatus,proto3" json:"workflowStatus,omitempty"`
	WorkflowTemplateId   int64    `protobuf:"varint,2,opt,name=workflowTemplateId,proto3" json:"workflowTemplateId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Statistics) Reset()         { *m = Statistics{} }
func (m *Statistics) String() string { return proto.CompactTextString(m) }
func (*Statistics) ProtoMessage()    {}
func (*Statistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{18}
}

func (m *Statistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Statistics.Unmarshal(m, b)
}
func (m *Statistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Statistics.Marshal(b, m, deterministic)
}
func (m *Statistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Statistics.Merge(m, src)
}
func (m *Statistics) XXX_Size() int {
	return xxx_messageInfo_Statistics.Size(m)
}
func (m *Statistics) XXX_DiscardUnknown() {
	xxx_messageInfo_Statistics.DiscardUnknown(m)
}

var xxx_messageInfo_Statistics proto.InternalMessageInfo

func (m *Statistics) GetWorkflowStatus() string {
	if m != nil {
		return m.WorkflowStatus
	}
	return ""
}

func (m *Statistics) GetWorkflowTemplateId() int64 {
	if m != nil {
		return m.WorkflowTemplateId
	}
	return 0
}

type AddWorkflowExecutionStatisticRequest struct {
	Namespace            string      `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Statistics           *Statistics `protobuf:"bytes,3,opt,name=statistics,proto3" json:"statistics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddWorkflowExecutionStatisticRequest) Reset()         { *m = AddWorkflowExecutionStatisticRequest{} }
func (m *AddWorkflowExecutionStatisticRequest) String() string { return proto.CompactTextString(m) }
func (*AddWorkflowExecutionStatisticRequest) ProtoMessage()    {}
func (*AddWorkflowExecutionStatisticRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{19}
}

func (m *AddWorkflowExecutionStatisticRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddWorkflowExecutionStatisticRequest.Unmarshal(m, b)
}
func (m *AddWorkflowExecutionStatisticRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddWorkflowExecutionStatisticRequest.Marshal(b, m, deterministic)
}
func (m *AddWorkflowExecutionStatisticRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddWorkflowExecutionStatisticRequest.Merge(m, src)
}
func (m *AddWorkflowExecutionStatisticRequest) XXX_Size() int {
	return xxx_messageInfo_AddWorkflowExecutionStatisticRequest.Size(m)
}
func (m *AddWorkflowExecutionStatisticRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddWorkflowExecutionStatisticRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddWorkflowExecutionStatisticRequest proto.InternalMessageInfo

func (m *AddWorkflowExecutionStatisticRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *AddWorkflowExecutionStatisticRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddWorkflowExecutionStatisticRequest) GetStatistics() *Statistics {
	if m != nil {
		return m.Statistics
	}
	return nil
}

type CronStartWorkflowExecutionStatisticRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	WorkflowTemplateId   int64    `protobuf:"varint,3,opt,name=workflowTemplateId,proto3" json:"workflowTemplateId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CronStartWorkflowExecutionStatisticRequest) Reset() {
	*m = CronStartWorkflowExecutionStatisticRequest{}
}
func (m *CronStartWorkflowExecutionStatisticRequest) String() string {
	return proto.CompactTextString(m)
}
func (*CronStartWorkflowExecutionStatisticRequest) ProtoMessage() {}
func (*CronStartWorkflowExecutionStatisticRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{20}
}

func (m *CronStartWorkflowExecutionStatisticRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CronStartWorkflowExecutionStatisticRequest.Unmarshal(m, b)
}
func (m *CronStartWorkflowExecutionStatisticRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CronStartWorkflowExecutionStatisticRequest.Marshal(b, m, deterministic)
}
func (m *CronStartWorkflowExecutionStatisticRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CronStartWorkflowExecutionStatisticRequest.Merge(m, src)
}
func (m *CronStartWorkflowExecutionStatisticRequest) XXX_Size() int {
	return xxx_messageInfo_CronStartWorkflowExecutionStatisticRequest.Size(m)
}
func (m *CronStartWorkflowExecutionStatisticRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CronStartWorkflowExecutionStatisticRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CronStartWorkflowExecutionStatisticRequest proto.InternalMessageInfo

func (m *CronStartWorkflowExecutionStatisticRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *CronStartWorkflowExecutionStatisticRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CronStartWorkflowExecutionStatisticRequest) GetWorkflowTemplateId() int64 {
	if m != nil {
		return m.WorkflowTemplateId
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateWorkflowExecutionRequest)(nil), "api.CreateWorkflowExecutionRequest")
	proto.RegisterType((*GetWorkflowExecutionRequest)(nil), "api.GetWorkflowExecutionRequest")
	proto.RegisterType((*GetArtifactRequest)(nil), "api.GetArtifactRequest")
	proto.RegisterType((*WatchWorkflowExecutionRequest)(nil), "api.WatchWorkflowExecutionRequest")
	proto.RegisterType((*ResubmitWorkflowExecutionRequest)(nil), "api.ResubmitWorkflowExecutionRequest")
	proto.RegisterType((*TerminateWorkflowExecutionRequest)(nil), "api.TerminateWorkflowExecutionRequest")
	proto.RegisterType((*GetWorkflowExecutionLogsRequest)(nil), "api.GetWorkflowExecutionLogsRequest")
	proto.RegisterType((*GetWorkflowExecutionMetricsRequest)(nil), "api.GetWorkflowExecutionMetricsRequest")
	proto.RegisterType((*GetWorkflowExecutionMetricsResponse)(nil), "api.GetWorkflowExecutionMetricsResponse")
	proto.RegisterType((*ListWorkflowExecutionsRequest)(nil), "api.ListWorkflowExecutionsRequest")
	proto.RegisterType((*ListWorkflowExecutionsResponse)(nil), "api.ListWorkflowExecutionsResponse")
	proto.RegisterType((*LogEntry)(nil), "api.LogEntry")
	proto.RegisterType((*WorkflowExecution)(nil), "api.WorkflowExecution")
	proto.RegisterType((*WorkflowExecutionParameter)(nil), "api.WorkflowExecutionParameter")
	proto.RegisterType((*ArtifactResponse)(nil), "api.ArtifactResponse")
	proto.RegisterType((*File)(nil), "api.File")
	proto.RegisterType((*ListFilesRequest)(nil), "api.ListFilesRequest")
	proto.RegisterType((*ListFilesResponse)(nil), "api.ListFilesResponse")
	proto.RegisterType((*Statistics)(nil), "api.Statistics")
	proto.RegisterType((*AddWorkflowExecutionStatisticRequest)(nil), "api.AddWorkflowExecutionStatisticRequest")
	proto.RegisterType((*CronStartWorkflowExecutionStatisticRequest)(nil), "api.CronStartWorkflowExecutionStatisticRequest")
}

func init() {
	proto.RegisterFile("workflow.proto", fileDescriptor_892c7f566756b0be)
}

var fileDescriptor_892c7f566756b0be = []byte{
	// 1376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xcd, 0x6e, 0x14, 0xc7,
	0x13, 0x57, 0x7b, 0x6d, 0xf0, 0xd6, 0xc2, 0x1f, 0x53, 0x7f, 0xb0, 0x37, 0x0b, 0x18, 0xa7, 0x0d,
	0xc4, 0x41, 0xca, 0x0e, 0x38, 0x1f, 0x8a, 0x10, 0x84, 0x18, 0xb0, 0x09, 0xc2, 0x04, 0x32, 0x36,
	0x1f, 0x37, 0xab, 0x3d, 0xdb, 0xbb, 0x1e, 0x79, 0x77, 0x66, 0x32, 0xdd, 0x8b, 0xd9, 0x58, 0xbe,
	0xa0, 0x1c, 0x92, 0x0b, 0x17, 0x2e, 0x51, 0x4e, 0x89, 0x94, 0x87, 0xc8, 0x29, 0xa7, 0x44, 0xca,
	0x3d, 0x87, 0x28, 0xf7, 0x3c, 0x41, 0x9e, 0x20, 0xea, 0x9e, 0x9e, 0xd9, 0xb1, 0x77, 0x66, 0x31,
	0x13, 0x73, 0x9a, 0xe9, 0xaa, 0xee, 0xaa, 0x5f, 0x7d, 0x75, 0x55, 0xc3, 0xff, 0xb6, 0xfc, 0x70,
	0xb3, 0xd9, 0xf6, 0xb7, 0xea, 0x41, 0xe8, 0x4b, 0x1f, 0x4b, 0x2c, 0x70, 0x6b, 0xa7, 0x5b, 0xbe,
	0xdf, 0x6a, 0x73, 0x8b, 0x05, 0xae, 0xc5, 0x3c, 0xcf, 0x97, 0x4c, 0xba, 0xbe, 0x27, 0xa2, 0x2d,
	0xb5, 0x53, 0x86, 0xab, 0x57, 0xeb, 0xdd, 0xa6, 0xc5, 0x3b, 0x81, 0xec, 0x19, 0xe6, 0x54, 0x2c,
	0x6f, 0x4d, 0xf2, 0x4e, 0xd0, 0x66, 0x92, 0x1b, 0xc6, 0x91, 0x0e, 0x97, 0xa1, 0xeb, 0x98, 0x55,
	0xa5, 0xcd, 0xd6, 0x79, 0x3b, 0x5a, 0xd0, 0xaf, 0x09, 0x4c, 0xdf, 0x0c, 0x39, 0x93, 0xfc, 0xb1,
	0x39, 0xbc, 0xf8, 0x8c, 0x3b, 0x5d, 0xa5, 0xd3, 0xe6, 0x5f, 0x76, 0xb9, 0x90, 0x78, 0x1a, 0xca,
	0x1e, 0xeb, 0x70, 0x11, 0x30, 0x87, 0x57, 0xc9, 0x0c, 0x99, 0x2b, 0xdb, 0x7d, 0x02, 0xde, 0x82,
	0xe3, 0x5b, 0x7b, 0x4f, 0x56, 0x47, 0x66, 0xc8, 0x5c, 0x65, 0x7e, 0xb2, 0xce, 0x02, 0xb7, 0x3e,
	0x28, 0x77, 0xf0, 0x00, 0xbd, 0x0f, 0xa7, 0x6e, 0x73, 0x59, 0x10, 0x02, 0xc2, 0xa8, 0x5a, 0x68,
	0xad, 0x65, 0x5b, 0xff, 0xd3, 0x27, 0x80, 0xb7, 0xb9, 0x5c, 0x08, 0xa5, 0xdb, 0x64, 0x8e, 0x2c,
	0x2c, 0x07, 0x27, 0xa0, 0xb4, 0xc9, 0x7b, 0xd5, 0x92, 0x26, 0xa9, 0x5f, 0xfa, 0x05, 0x9c, 0x79,
	0xcc, 0xa4, 0xb3, 0x71, 0x80, 0x60, 0x57, 0x61, 0xc6, 0xe6, 0xa2, 0xbb, 0xde, 0x71, 0x0f, 0xd2,
	0x05, 0x0f, 0xe1, 0xed, 0x55, 0x1e, 0x76, 0x5c, 0xaf, 0x78, 0x70, 0xb3, 0xc4, 0xbe, 0x24, 0x70,
	0x36, 0x2b, 0x56, 0xcb, 0x7e, 0x4b, 0x14, 0xf7, 0x73, 0x15, 0x0e, 0x07, 0x7e, 0xe3, 0x73, 0x45,
	0x8e, 0x7c, 0x1d, 0x2f, 0xf1, 0x1c, 0x1c, 0x75, 0x7c, 0x4f, 0x32, 0xd7, 0xe3, 0xa1, 0xe6, 0x8f,
	0x6a, 0xfe, 0x6e, 0x22, 0x0d, 0x80, 0x66, 0x81, 0xba, 0xa7, 0x13, 0xff, 0x4d, 0xe0, 0xa2, 0xcb,
	0x30, 0x3b, 0x54, 0xa3, 0x08, 0x7c, 0x4f, 0x70, 0x3c, 0x0f, 0x87, 0xa3, 0xea, 0x13, 0x55, 0x32,
	0x53, 0x9a, 0xab, 0xcc, 0x57, 0x74, 0x55, 0x44, 0xdb, 0xec, 0x98, 0x47, 0xff, 0x22, 0x70, 0x66,
	0xd9, 0x15, 0x83, 0xf2, 0xf6, 0x89, 0xfd, 0x12, 0xfc, 0x3f, 0xae, 0xaa, 0x55, 0x53, 0xfc, 0x0f,
	0xdd, 0x86, 0x31, 0x25, 0x8b, 0x85, 0x1f, 0xc3, 0xd4, 0x5e, 0xf2, 0x23, 0x1e, 0x0a, 0x55, 0xbe,
	0x91, 0xa5, 0x79, 0x6c, 0xac, 0xc1, 0x78, 0xc0, 0x5a, 0x7c, 0xc5, 0xfd, 0x2a, 0x0a, 0xc6, 0x98,
	0x9d, 0xac, 0x95, 0x0f, 0xd5, 0x7f, 0x75, 0x4c, 0xd3, 0xf5, 0x3f, 0xfd, 0x9d, 0xc0, 0x74, 0x9e,
	0x6d, 0xc6, 0x4b, 0x27, 0x60, 0xcc, 0xf1, 0xbb, 0x9e, 0xd4, 0x86, 0x8d, 0xd9, 0xd1, 0x02, 0x97,
	0x00, 0x07, 0xae, 0x0a, 0x51, 0x1d, 0xd1, 0x6e, 0xcc, 0xbb, 0x5c, 0x32, 0x4e, 0x24, 0xa0, 0x4a,
	0x7d, 0x50, 0x4a, 0xa3, 0xfa, 0x0a, 0x63, 0x41, 0xb4, 0xc0, 0x69, 0x00, 0xe9, 0x4b, 0xd6, 0xbe,
	0xa9, 0xc1, 0x44, 0x46, 0xa4, 0x28, 0xf4, 0x06, 0x8c, 0x2f, 0xfb, 0xad, 0x45, 0x4f, 0x86, 0x3d,
	0x15, 0x10, 0xe9, 0x76, 0xb8, 0x90, 0xac, 0x13, 0xc4, 0x01, 0x49, 0x08, 0x2a, 0x71, 0x54, 0x86,
	0x72, 0x4f, 0x9a, 0x20, 0xc4, 0x4b, 0xfa, 0xcf, 0x08, 0x1c, 0x1f, 0xc0, 0xad, 0xa4, 0x39, 0xfa,
	0x1e, 0x6e, 0x2c, 0xc8, 0x58, 0x5a, 0x42, 0x50, 0xd7, 0x50, 0x37, 0x09, 0xa7, 0xfa, 0x4d, 0x92,
	0xb5, 0x94, 0x4a, 0x56, 0x65, 0xd3, 0x06, 0x13, 0x71, 0x89, 0x44, 0x0b, 0x25, 0x59, 0x48, 0x16,
	0x46, 0x92, 0xc7, 0x22, 0xc9, 0x09, 0x41, 0x59, 0xdc, 0x74, 0x3d, 0x57, 0x6c, 0x68, 0xf6, 0x21,
	0xcd, 0x4e, 0x51, 0x54, 0xb0, 0x3b, 0xcc, 0x73, 0x9b, 0x5c, 0xc8, 0xea, 0x61, 0xcd, 0x4d, 0xd6,
	0x78, 0x1d, 0x20, 0x60, 0x21, 0xeb, 0x70, 0xc9, 0x43, 0x51, 0x1d, 0xd7, 0x71, 0x39, 0x9b, 0x1d,
	0x97, 0x07, 0xf1, 0x3e, 0x3b, 0x75, 0x04, 0x17, 0x60, 0x62, 0x6f, 0x92, 0x55, 0xcb, 0xba, 0x77,
	0x9c, 0xdc, 0x25, 0x26, 0x66, 0xda, 0x03, 0xdb, 0xf1, 0x3c, 0x1c, 0xd2, 0xfd, 0x4c, 0x54, 0x41,
	0xeb, 0x3f, 0xaa, 0x0f, 0xde, 0xe5, 0xbd, 0x47, 0xac, 0xdd, 0xe5, 0xb6, 0x61, 0xd2, 0x25, 0xa8,
	0xe5, 0x63, 0x4a, 0x9c, 0x49, 0x76, 0x3b, 0xf3, 0xa9, 0x12, 0x61, 0x9c, 0x1e, 0x2d, 0xe8, 0x05,
	0x98, 0xe8, 0x37, 0x15, 0x93, 0xbc, 0x08, 0xa3, 0x0d, 0x26, 0x99, 0x3e, 0x7d, 0xc4, 0xd6, 0xff,
	0xf4, 0x57, 0x02, 0xa3, 0x4b, 0x6e, 0xdb, 0x14, 0x84, 0xdc, 0x88, 0x45, 0xab, 0xff, 0xcc, 0x8b,
	0xe6, 0x34, 0x94, 0xf9, 0x33, 0xc9, 0xbd, 0x54, 0x01, 0xf6, 0x09, 0xea, 0x84, 0x88, 0xcb, 0xad,
	0x64, 0xeb, 0x7f, 0x9c, 0x81, 0x8a, 0x49, 0xa9, 0xd5, 0x5e, 0xc0, 0x4d, 0x64, 0xd3, 0x24, 0xa4,
	0x70, 0xa4, 0xcd, 0x84, 0xbc, 0xe7, 0x37, 0xdc, 0xa6, 0xcb, 0x1b, 0x26, 0xba, 0xbb, 0x68, 0x4a,
	0x6f, 0xc3, 0x0d, 0xb9, 0x23, 0xfd, 0xb0, 0xa7, 0x03, 0x3c, 0x6e, 0xf7, 0x09, 0xf4, 0x09, 0x4c,
	0xa8, 0xca, 0x55, 0x96, 0xfc, 0x87, 0x4b, 0x34, 0xf6, 0x41, 0xa9, 0xef, 0x03, 0xba, 0x0a, 0xc7,
	0x53, 0x92, 0x8d, 0x27, 0xcf, 0xc2, 0x58, 0x53, 0x11, 0xcc, 0x55, 0x59, 0xd6, 0xb1, 0x54, 0x5b,
	0xec, 0x88, 0xae, 0xb2, 0x35, 0x60, 0x21, 0xf7, 0xe4, 0x03, 0x25, 0x2f, 0xd2, 0x91, 0xa2, 0xd0,
	0x06, 0xc0, 0x8a, 0x9a, 0x98, 0x84, 0x74, 0x1d, 0x81, 0x17, 0xfa, 0x23, 0x96, 0xa2, 0x76, 0x85,
	0x81, 0xbb, 0x87, 0x8a, 0xf5, 0xfe, 0x3d, 0x13, 0xe7, 0xd5, 0x9d, 0xa8, 0xd8, 0x4a, 0x76, 0x06,
	0x87, 0x7e, 0x4b, 0xe0, 0xdc, 0x42, 0xa3, 0x31, 0x90, 0x50, 0x89, 0xea, 0xe2, 0xae, 0xb2, 0x00,
	0x44, 0x62, 0x80, 0x76, 0x58, 0x65, 0xfe, 0x98, 0x76, 0x43, 0xdf, 0x2e, 0x3b, 0xb5, 0x85, 0xbe,
	0x20, 0x70, 0xf1, 0x66, 0xa8, 0x75, 0x87, 0xf2, 0x4d, 0x20, 0xca, 0x76, 0x4e, 0x29, 0xcf, 0x39,
	0xf3, 0xcf, 0x27, 0xe0, 0x58, 0x8c, 0x63, 0x85, 0x87, 0x4f, 0x5d, 0x87, 0xe3, 0x0f, 0x04, 0xa6,
	0x72, 0xa6, 0x4c, 0x9c, 0xd5, 0xd6, 0x0d, 0x9f, 0x41, 0x6b, 0x39, 0xb7, 0x3d, 0xfd, 0xec, 0xf9,
	0x1f, 0x7f, 0xbf, 0x1c, 0xb9, 0x41, 0xdf, 0x53, 0xf3, 0xb2, 0xb0, 0x9e, 0x5e, 0x5e, 0xe7, 0x92,
	0x5d, 0xb6, 0xb6, 0x13, 0x93, 0x76, 0xac, 0x64, 0x28, 0xe6, 0x49, 0x43, 0xb8, 0x32, 0x38, 0x81,
	0xe2, 0x0b, 0x02, 0x27, 0xb2, 0xfa, 0x39, 0xce, 0x68, 0xd5, 0x43, 0xa6, 0xd3, 0x5c, 0x70, 0x57,
	0x35, 0xb8, 0x8f, 0xf0, 0x83, 0xd7, 0x02, 0x17, 0xf1, 0x77, 0xf0, 0x3b, 0x02, 0x93, 0xd9, 0x5d,
	0x13, 0xa9, 0x56, 0x38, 0x74, 0x5c, 0xa8, 0xcd, 0x0e, 0xdd, 0x13, 0xd5, 0x1b, 0xfd, 0x50, 0x23,
	0xb4, 0xf0, 0xf5, 0xdc, 0x87, 0xdf, 0x13, 0x98, 0xcc, 0x9e, 0x81, 0x0d, 0xb4, 0xa1, 0x03, 0x72,
	0xae, 0xbf, 0x6e, 0x68, 0x34, 0x57, 0xf1, 0x4a, 0x11, 0x7f, 0x59, 0x5b, 0x4a, 0xe7, 0x25, 0x82,
	0xbf, 0x10, 0xa8, 0xe6, 0xcd, 0xa7, 0x78, 0x2e, 0x37, 0x98, 0xa9, 0xf1, 0xb5, 0x16, 0xf5, 0x90,
	0xb8, 0xd1, 0xd3, 0x4d, 0x8d, 0x8b, 0xa3, 0x53, 0x08, 0x57, 0xe0, 0x37, 0x84, 0xb5, 0x6d, 0xa6,
	0xc6, 0x1d, 0x2b, 0x19, 0x5b, 0x85, 0xb5, 0xbd, 0x6b, 0x84, 0xdd, 0xb1, 0xda, 0x7e, 0x4b, 0x5c,
	0x22, 0xf8, 0x1b, 0xc9, 0x7e, 0x0c, 0x99, 0xc9, 0x12, 0xdf, 0xc9, 0xb5, 0x61, 0xf7, 0xb4, 0x5b,
	0x9b, 0x7b, 0xf5, 0x46, 0x93, 0x07, 0x2b, 0xda, 0xc2, 0x7b, 0x78, 0xf7, 0x20, 0x2c, 0x34, 0x23,
	0x2d, 0xfe, 0x48, 0xe0, 0xad, 0xdc, 0x67, 0x0d, 0x9e, 0xd7, 0xe0, 0x5e, 0xf5, 0xec, 0xc9, 0xcd,
	0x95, 0x45, 0x8d, 0xf8, 0x7a, 0xed, 0x5a, 0x21, 0xc4, 0xa1, 0x51, 0x8b, 0x3f, 0x11, 0xa8, 0xe5,
	0x3f, 0x92, 0xf0, 0x82, 0xd6, 0xfe, 0xca, 0x57, 0x54, 0x6d, 0xb2, 0x1e, 0xbd, 0xcb, 0xeb, 0xf1,
	0xbb, 0xbc, 0xbe, 0xa8, 0xde, 0xe5, 0x74, 0x49, 0xa3, 0xfc, 0xb4, 0xf6, 0x49, 0x21, 0x94, 0x32,
	0xd6, 0xab, 0x2e, 0xa7, 0x4a, 0xea, 0x39, 0x8b, 0x53, 0x71, 0x64, 0xf7, 0x3c, 0x70, 0x6b, 0xd1,
	0xd8, 0xb4, 0x77, 0x42, 0xa1, 0xf7, 0x35, 0x8e, 0x3b, 0x78, 0xbb, 0x10, 0x0e, 0x66, 0xc4, 0x09,
	0x6b, 0x7b, 0x93, 0xf7, 0xae, 0x5d, 0xbc, 0xb8, 0x83, 0xdf, 0x10, 0x28, 0x27, 0xed, 0x1b, 0x4f,
	0x26, 0x77, 0x4d, 0x7a, 0x50, 0x30, 0xb1, 0x1b, 0xe8, 0xf2, 0x74, 0x59, 0xa3, 0x59, 0xc2, 0x5b,
	0x85, 0xd0, 0xe8, 0x41, 0xc0, 0xda, 0x56, 0x43, 0x84, 0x86, 0xf2, 0x33, 0x81, 0xe9, 0xa1, 0xcd,
	0x58, 0xe0, 0xbb, 0x91, 0x57, 0xf6, 0xd1, 0xb1, 0x73, 0x23, 0x69, 0x2a, 0x84, 0x5e, 0x2f, 0x84,
	0xb9, 0xdf, 0xaf, 0xaf, 0xa4, 0x7a, 0x37, 0xfe, 0x49, 0x60, 0x76, 0x1f, 0xbd, 0x1b, 0x2d, 0xd3,
	0x22, 0xf7, 0xdb, 0xe5, 0x73, 0xad, 0x68, 0x69, 0x2b, 0x18, 0xae, 0x15, 0xb2, 0xc2, 0x09, 0x7d,
	0x6f, 0x4d, 0xbf, 0x1c, 0xd6, 0xfa, 0x46, 0x58, 0xdb, 0x83, 0x33, 0xc0, 0xce, 0xfa, 0x21, 0xad,
	0xf8, 0xfd, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x1c, 0xad, 0x40, 0xe3, 0x12, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WorkflowServiceClient is the client API for WorkflowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkflowServiceClient interface {
	// Creates a Workflow
	CreateWorkflowExecution(ctx context.Context, in *CreateWorkflowExecutionRequest, opts ...grpc.CallOption) (*WorkflowExecution, error)
	GetWorkflowExecution(ctx context.Context, in *GetWorkflowExecutionRequest, opts ...grpc.CallOption) (*WorkflowExecution, error)
	ListWorkflowExecutions(ctx context.Context, in *ListWorkflowExecutionsRequest, opts ...grpc.CallOption) (*ListWorkflowExecutionsResponse, error)
	WatchWorkflowExecution(ctx context.Context, in *WatchWorkflowExecutionRequest, opts ...grpc.CallOption) (WorkflowService_WatchWorkflowExecutionClient, error)
	GetWorkflowExecutionLogs(ctx context.Context, in *GetWorkflowExecutionLogsRequest, opts ...grpc.CallOption) (WorkflowService_GetWorkflowExecutionLogsClient, error)
	GetWorkflowExecutionMetrics(ctx context.Context, in *GetWorkflowExecutionMetricsRequest, opts ...grpc.CallOption) (*GetWorkflowExecutionMetricsResponse, error)
	ResubmitWorkflowExecution(ctx context.Context, in *ResubmitWorkflowExecutionRequest, opts ...grpc.CallOption) (*WorkflowExecution, error)
	TerminateWorkflowExecution(ctx context.Context, in *TerminateWorkflowExecutionRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetArtifact(ctx context.Context, in *GetArtifactRequest, opts ...grpc.CallOption) (*ArtifactResponse, error)
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	AddWorkflowExecutionStatistics(ctx context.Context, in *AddWorkflowExecutionStatisticRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	CronStartWorkflowExecutionStatistic(ctx context.Context, in *CronStartWorkflowExecutionStatisticRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type workflowServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkflowServiceClient(cc grpc.ClientConnInterface) WorkflowServiceClient {
	return &workflowServiceClient{cc}
}

func (c *workflowServiceClient) CreateWorkflowExecution(ctx context.Context, in *CreateWorkflowExecutionRequest, opts ...grpc.CallOption) (*WorkflowExecution, error) {
	out := new(WorkflowExecution)
	err := c.cc.Invoke(ctx, "/api.WorkflowService/CreateWorkflowExecution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) GetWorkflowExecution(ctx context.Context, in *GetWorkflowExecutionRequest, opts ...grpc.CallOption) (*WorkflowExecution, error) {
	out := new(WorkflowExecution)
	err := c.cc.Invoke(ctx, "/api.WorkflowService/GetWorkflowExecution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ListWorkflowExecutions(ctx context.Context, in *ListWorkflowExecutionsRequest, opts ...grpc.CallOption) (*ListWorkflowExecutionsResponse, error) {
	out := new(ListWorkflowExecutionsResponse)
	err := c.cc.Invoke(ctx, "/api.WorkflowService/ListWorkflowExecutions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) WatchWorkflowExecution(ctx context.Context, in *WatchWorkflowExecutionRequest, opts ...grpc.CallOption) (WorkflowService_WatchWorkflowExecutionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WorkflowService_serviceDesc.Streams[0], "/api.WorkflowService/WatchWorkflowExecution", opts...)
	if err != nil {
		return nil, err
	}
	x := &workflowServiceWatchWorkflowExecutionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WorkflowService_WatchWorkflowExecutionClient interface {
	Recv() (*WorkflowExecution, error)
	grpc.ClientStream
}

type workflowServiceWatchWorkflowExecutionClient struct {
	grpc.ClientStream
}

func (x *workflowServiceWatchWorkflowExecutionClient) Recv() (*WorkflowExecution, error) {
	m := new(WorkflowExecution)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *workflowServiceClient) GetWorkflowExecutionLogs(ctx context.Context, in *GetWorkflowExecutionLogsRequest, opts ...grpc.CallOption) (WorkflowService_GetWorkflowExecutionLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WorkflowService_serviceDesc.Streams[1], "/api.WorkflowService/GetWorkflowExecutionLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &workflowServiceGetWorkflowExecutionLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WorkflowService_GetWorkflowExecutionLogsClient interface {
	Recv() (*LogEntry, error)
	grpc.ClientStream
}

type workflowServiceGetWorkflowExecutionLogsClient struct {
	grpc.ClientStream
}

func (x *workflowServiceGetWorkflowExecutionLogsClient) Recv() (*LogEntry, error) {
	m := new(LogEntry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *workflowServiceClient) GetWorkflowExecutionMetrics(ctx context.Context, in *GetWorkflowExecutionMetricsRequest, opts ...grpc.CallOption) (*GetWorkflowExecutionMetricsResponse, error) {
	out := new(GetWorkflowExecutionMetricsResponse)
	err := c.cc.Invoke(ctx, "/api.WorkflowService/GetWorkflowExecutionMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ResubmitWorkflowExecution(ctx context.Context, in *ResubmitWorkflowExecutionRequest, opts ...grpc.CallOption) (*WorkflowExecution, error) {
	out := new(WorkflowExecution)
	err := c.cc.Invoke(ctx, "/api.WorkflowService/ResubmitWorkflowExecution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) TerminateWorkflowExecution(ctx context.Context, in *TerminateWorkflowExecutionRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.WorkflowService/TerminateWorkflowExecution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) GetArtifact(ctx context.Context, in *GetArtifactRequest, opts ...grpc.CallOption) (*ArtifactResponse, error) {
	out := new(ArtifactResponse)
	err := c.cc.Invoke(ctx, "/api.WorkflowService/GetArtifact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, "/api.WorkflowService/ListFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) AddWorkflowExecutionStatistics(ctx context.Context, in *AddWorkflowExecutionStatisticRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.WorkflowService/AddWorkflowExecutionStatistics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) CronStartWorkflowExecutionStatistic(ctx context.Context, in *CronStartWorkflowExecutionStatisticRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.WorkflowService/CronStartWorkflowExecutionStatistic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowServiceServer is the server API for WorkflowService service.
type WorkflowServiceServer interface {
	// Creates a Workflow
	CreateWorkflowExecution(context.Context, *CreateWorkflowExecutionRequest) (*WorkflowExecution, error)
	GetWorkflowExecution(context.Context, *GetWorkflowExecutionRequest) (*WorkflowExecution, error)
	ListWorkflowExecutions(context.Context, *ListWorkflowExecutionsRequest) (*ListWorkflowExecutionsResponse, error)
	WatchWorkflowExecution(*WatchWorkflowExecutionRequest, WorkflowService_WatchWorkflowExecutionServer) error
	GetWorkflowExecutionLogs(*GetWorkflowExecutionLogsRequest, WorkflowService_GetWorkflowExecutionLogsServer) error
	GetWorkflowExecutionMetrics(context.Context, *GetWorkflowExecutionMetricsRequest) (*GetWorkflowExecutionMetricsResponse, error)
	ResubmitWorkflowExecution(context.Context, *ResubmitWorkflowExecutionRequest) (*WorkflowExecution, error)
	TerminateWorkflowExecution(context.Context, *TerminateWorkflowExecutionRequest) (*empty.Empty, error)
	GetArtifact(context.Context, *GetArtifactRequest) (*ArtifactResponse, error)
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	AddWorkflowExecutionStatistics(context.Context, *AddWorkflowExecutionStatisticRequest) (*empty.Empty, error)
	CronStartWorkflowExecutionStatistic(context.Context, *CronStartWorkflowExecutionStatisticRequest) (*empty.Empty, error)
}

// UnimplementedWorkflowServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWorkflowServiceServer struct {
}

func (*UnimplementedWorkflowServiceServer) CreateWorkflowExecution(ctx context.Context, req *CreateWorkflowExecutionRequest) (*WorkflowExecution, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWorkflowExecution not implemented")
}
func (*UnimplementedWorkflowServiceServer) GetWorkflowExecution(ctx context.Context, req *GetWorkflowExecutionRequest) (*WorkflowExecution, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkflowExecution not implemented")
}
func (*UnimplementedWorkflowServiceServer) ListWorkflowExecutions(ctx context.Context, req *ListWorkflowExecutionsRequest) (*ListWorkflowExecutionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkflowExecutions not implemented")
}
func (*UnimplementedWorkflowServiceServer) WatchWorkflowExecution(req *WatchWorkflowExecutionRequest, srv WorkflowService_WatchWorkflowExecutionServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchWorkflowExecution not implemented")
}
func (*UnimplementedWorkflowServiceServer) GetWorkflowExecutionLogs(req *GetWorkflowExecutionLogsRequest, srv WorkflowService_GetWorkflowExecutionLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetWorkflowExecutionLogs not implemented")
}
func (*UnimplementedWorkflowServiceServer) GetWorkflowExecutionMetrics(ctx context.Context, req *GetWorkflowExecutionMetricsRequest) (*GetWorkflowExecutionMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkflowExecutionMetrics not implemented")
}
func (*UnimplementedWorkflowServiceServer) ResubmitWorkflowExecution(ctx context.Context, req *ResubmitWorkflowExecutionRequest) (*WorkflowExecution, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResubmitWorkflowExecution not implemented")
}
func (*UnimplementedWorkflowServiceServer) TerminateWorkflowExecution(ctx context.Context, req *TerminateWorkflowExecutionRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TerminateWorkflowExecution not implemented")
}
func (*UnimplementedWorkflowServiceServer) GetArtifact(ctx context.Context, req *GetArtifactRequest) (*ArtifactResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArtifact not implemented")
}
func (*UnimplementedWorkflowServiceServer) ListFiles(ctx context.Context, req *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFiles not implemented")
}
func (*UnimplementedWorkflowServiceServer) AddWorkflowExecutionStatistics(ctx context.Context, req *AddWorkflowExecutionStatisticRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddWorkflowExecutionStatistics not implemented")
}
func (*UnimplementedWorkflowServiceServer) CronStartWorkflowExecutionStatistic(ctx context.Context, req *CronStartWorkflowExecutionStatisticRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CronStartWorkflowExecutionStatistic not implemented")
}

func RegisterWorkflowServiceServer(s *grpc.Server, srv WorkflowServiceServer) {
	s.RegisterService(&_WorkflowService_serviceDesc, srv)
}

func _WorkflowService_CreateWorkflowExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkflowExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).CreateWorkflowExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.WorkflowService/CreateWorkflowExecution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).CreateWorkflowExecution(ctx, req.(*CreateWorkflowExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_GetWorkflowExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkflowExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).GetWorkflowExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.WorkflowService/GetWorkflowExecution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).GetWorkflowExecution(ctx, req.(*GetWorkflowExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ListWorkflowExecutions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkflowExecutionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ListWorkflowExecutions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.WorkflowService/ListWorkflowExecutions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ListWorkflowExecutions(ctx, req.(*ListWorkflowExecutionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_WatchWorkflowExecution_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchWorkflowExecutionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkflowServiceServer).WatchWorkflowExecution(m, &workflowServiceWatchWorkflowExecutionServer{stream})
}

type WorkflowService_WatchWorkflowExecutionServer interface {
	Send(*WorkflowExecution) error
	grpc.ServerStream
}

type workflowServiceWatchWorkflowExecutionServer struct {
	grpc.ServerStream
}

func (x *workflowServiceWatchWorkflowExecutionServer) Send(m *WorkflowExecution) error {
	return x.ServerStream.SendMsg(m)
}

func _WorkflowService_GetWorkflowExecutionLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetWorkflowExecutionLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkflowServiceServer).GetWorkflowExecutionLogs(m, &workflowServiceGetWorkflowExecutionLogsServer{stream})
}

type WorkflowService_GetWorkflowExecutionLogsServer interface {
	Send(*LogEntry) error
	grpc.ServerStream
}

type workflowServiceGetWorkflowExecutionLogsServer struct {
	grpc.ServerStream
}

func (x *workflowServiceGetWorkflowExecutionLogsServer) Send(m *LogEntry) error {
	return x.ServerStream.SendMsg(m)
}

func _WorkflowService_GetWorkflowExecutionMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkflowExecutionMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).GetWorkflowExecutionMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.WorkflowService/GetWorkflowExecutionMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).GetWorkflowExecutionMetrics(ctx, req.(*GetWorkflowExecutionMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ResubmitWorkflowExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResubmitWorkflowExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ResubmitWorkflowExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.WorkflowService/ResubmitWorkflowExecution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ResubmitWorkflowExecution(ctx, req.(*ResubmitWorkflowExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_TerminateWorkflowExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateWorkflowExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).TerminateWorkflowExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.WorkflowService/TerminateWorkflowExecution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).TerminateWorkflowExecution(ctx, req.(*TerminateWorkflowExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_GetArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).GetArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.WorkflowService/GetArtifact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).GetArtifact(ctx, req.(*GetArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.WorkflowService/ListFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_AddWorkflowExecutionStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWorkflowExecutionStatisticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).AddWorkflowExecutionStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.WorkflowService/AddWorkflowExecutionStatistics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).AddWorkflowExecutionStatistics(ctx, req.(*AddWorkflowExecutionStatisticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_CronStartWorkflowExecutionStatistic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CronStartWorkflowExecutionStatisticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).CronStartWorkflowExecutionStatistic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.WorkflowService/CronStartWorkflowExecutionStatistic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).CronStartWorkflowExecutionStatistic(ctx, req.(*CronStartWorkflowExecutionStatisticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WorkflowService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.WorkflowService",
	HandlerType: (*WorkflowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWorkflowExecution",
			Handler:    _WorkflowService_CreateWorkflowExecution_Handler,
		},
		{
			MethodName: "GetWorkflowExecution",
			Handler:    _WorkflowService_GetWorkflowExecution_Handler,
		},
		{
			MethodName: "ListWorkflowExecutions",
			Handler:    _WorkflowService_ListWorkflowExecutions_Handler,
		},
		{
			MethodName: "GetWorkflowExecutionMetrics",
			Handler:    _WorkflowService_GetWorkflowExecutionMetrics_Handler,
		},
		{
			MethodName: "ResubmitWorkflowExecution",
			Handler:    _WorkflowService_ResubmitWorkflowExecution_Handler,
		},
		{
			MethodName: "TerminateWorkflowExecution",
			Handler:    _WorkflowService_TerminateWorkflowExecution_Handler,
		},
		{
			MethodName: "GetArtifact",
			Handler:    _WorkflowService_GetArtifact_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _WorkflowService_ListFiles_Handler,
		},
		{
			MethodName: "AddWorkflowExecutionStatistics",
			Handler:    _WorkflowService_AddWorkflowExecutionStatistics_Handler,
		},
		{
			MethodName: "CronStartWorkflowExecutionStatistic",
			Handler:    _WorkflowService_CronStartWorkflowExecutionStatistic_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchWorkflowExecution",
			Handler:       _WorkflowService_WatchWorkflowExecution_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetWorkflowExecutionLogs",
			Handler:       _WorkflowService_GetWorkflowExecutionLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "workflow.proto",
}
