// Code generated by protoc-gen-go. DO NOT EDIT.
// source: workspace_template.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateWorkspaceTemplateRequest struct {
	Namespace            string             `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	WorkspaceTemplate    *WorkspaceTemplate `protobuf:"bytes,2,opt,name=workspaceTemplate,proto3" json:"workspaceTemplate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreateWorkspaceTemplateRequest) Reset()         { *m = CreateWorkspaceTemplateRequest{} }
func (m *CreateWorkspaceTemplateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateWorkspaceTemplateRequest) ProtoMessage()    {}
func (*CreateWorkspaceTemplateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b00f4e2babeeb4c, []int{0}
}

func (m *CreateWorkspaceTemplateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWorkspaceTemplateRequest.Unmarshal(m, b)
}
func (m *CreateWorkspaceTemplateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWorkspaceTemplateRequest.Marshal(b, m, deterministic)
}
func (m *CreateWorkspaceTemplateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWorkspaceTemplateRequest.Merge(m, src)
}
func (m *CreateWorkspaceTemplateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateWorkspaceTemplateRequest.Size(m)
}
func (m *CreateWorkspaceTemplateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWorkspaceTemplateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWorkspaceTemplateRequest proto.InternalMessageInfo

func (m *CreateWorkspaceTemplateRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *CreateWorkspaceTemplateRequest) GetWorkspaceTemplate() *WorkspaceTemplate {
	if m != nil {
		return m.WorkspaceTemplate
	}
	return nil
}

type WorkspaceTemplate struct {
	Uid                  string            `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version              int64             `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Manifest             string            `protobuf:"bytes,4,opt,name=manifest,proto3" json:"manifest,omitempty"`
	IsLatest             bool              `protobuf:"varint,5,opt,name=isLatest,proto3" json:"isLatest,omitempty"`
	CreatedAt            string            `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	WorkflowTemplate     *WorkflowTemplate `protobuf:"bytes,7,opt,name=workflowTemplate,proto3" json:"workflowTemplate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *WorkspaceTemplate) Reset()         { *m = WorkspaceTemplate{} }
func (m *WorkspaceTemplate) String() string { return proto.CompactTextString(m) }
func (*WorkspaceTemplate) ProtoMessage()    {}
func (*WorkspaceTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b00f4e2babeeb4c, []int{1}
}

func (m *WorkspaceTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkspaceTemplate.Unmarshal(m, b)
}
func (m *WorkspaceTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkspaceTemplate.Marshal(b, m, deterministic)
}
func (m *WorkspaceTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkspaceTemplate.Merge(m, src)
}
func (m *WorkspaceTemplate) XXX_Size() int {
	return xxx_messageInfo_WorkspaceTemplate.Size(m)
}
func (m *WorkspaceTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkspaceTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_WorkspaceTemplate proto.InternalMessageInfo

func (m *WorkspaceTemplate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *WorkspaceTemplate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WorkspaceTemplate) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *WorkspaceTemplate) GetManifest() string {
	if m != nil {
		return m.Manifest
	}
	return ""
}

func (m *WorkspaceTemplate) GetIsLatest() bool {
	if m != nil {
		return m.IsLatest
	}
	return false
}

func (m *WorkspaceTemplate) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *WorkspaceTemplate) GetWorkflowTemplate() *WorkflowTemplate {
	if m != nil {
		return m.WorkflowTemplate
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateWorkspaceTemplateRequest)(nil), "api.CreateWorkspaceTemplateRequest")
	proto.RegisterType((*WorkspaceTemplate)(nil), "api.WorkspaceTemplate")
}

func init() {
	proto.RegisterFile("workspace_template.proto", fileDescriptor_1b00f4e2babeeb4c)
}

var fileDescriptor_1b00f4e2babeeb4c = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x4e, 0x02, 0x31,
	0x14, 0x4e, 0x19, 0xe4, 0xa7, 0x6e, 0xa0, 0x89, 0xd2, 0x8c, 0xc4, 0x4c, 0xc6, 0xcd, 0x6c, 0x64,
	0x02, 0xee, 0xdc, 0xa1, 0x2e, 0x5c, 0xb8, 0x1a, 0x4d, 0x5c, 0x9a, 0x02, 0x0f, 0xd2, 0xc8, 0x4c,
	0xeb, 0xb4, 0x40, 0x8c, 0x71, 0x63, 0xbc, 0x81, 0x17, 0xf0, 0x22, 0x9e, 0xc2, 0x2b, 0xb8, 0xf4,
	0x10, 0xa6, 0x05, 0x46, 0x43, 0x83, 0xbb, 0xbe, 0xf7, 0xbd, 0xaf, 0x5f, 0xbe, 0xf7, 0x3d, 0x4c,
	0x17, 0x22, 0xbf, 0x57, 0x92, 0x0d, 0xe1, 0x4e, 0x43, 0x2a, 0xa7, 0x4c, 0x43, 0x47, 0xe6, 0x42,
	0x0b, 0xe2, 0x31, 0xc9, 0xfd, 0xf6, 0x44, 0x88, 0xc9, 0x14, 0x62, 0x26, 0x79, 0xcc, 0xb2, 0x4c,
	0x68, 0xa6, 0xb9, 0xc8, 0xd4, 0x72, 0xc4, 0x6f, 0x19, 0xf2, 0x78, 0x2a, 0x16, 0x1b, 0x5c, 0xff,
	0x60, 0x45, 0xb3, 0xd5, 0x60, 0x36, 0x8e, 0x21, 0x95, 0xfa, 0x71, 0x09, 0x86, 0xaf, 0x08, 0x1f,
	0x9e, 0xe7, 0xc0, 0x34, 0xdc, 0xae, 0xb5, 0x6f, 0x56, 0xf4, 0x04, 0x1e, 0x66, 0xa0, 0x34, 0x69,
	0xe3, 0x7a, 0xc6, 0x52, 0xb0, 0x18, 0x45, 0x01, 0x8a, 0xea, 0xc9, 0x6f, 0x83, 0x5c, 0xe0, 0xe6,
	0x62, 0x93, 0x49, 0x4b, 0x01, 0x8a, 0x76, 0x7b, 0xfb, 0x1d, 0x26, 0x79, 0xc7, 0xfd, 0xd7, 0x25,
	0x84, 0xdf, 0x08, 0x37, 0x9d, 0x41, 0xd2, 0xc0, 0xde, 0x8c, 0x8f, 0x56, 0x9a, 0xe6, 0x49, 0x08,
	0x2e, 0x1b, 0x69, 0x2b, 0x50, 0x4f, 0xec, 0x9b, 0x50, 0x5c, 0x9d, 0x43, 0xae, 0xb8, 0xc8, 0xa8,
	0x17, 0xa0, 0xc8, 0x4b, 0xd6, 0x25, 0xf1, 0x71, 0x2d, 0x65, 0x19, 0x1f, 0x83, 0xd2, 0xb4, 0x6c,
	0x19, 0x45, 0x6d, 0x30, 0xae, 0xae, 0x98, 0x36, 0xd8, 0x4e, 0x80, 0xa2, 0x5a, 0x52, 0xd4, 0xc6,
	0xf1, 0xd0, 0xee, 0x64, 0xd4, 0xd7, 0xb4, 0xb2, 0x74, 0x5c, 0x34, 0x48, 0x1f, 0x37, 0xd6, 0xab,
	0x2e, 0x0c, 0x57, 0xad, 0xe1, 0xbd, 0xc2, 0xf0, 0x5f, 0x30, 0x71, 0xc6, 0x7b, 0x1f, 0x08, 0x53,
	0xc7, 0xee, 0x35, 0xe4, 0x73, 0x3e, 0x04, 0xf2, 0x8e, 0x70, 0x6b, 0x4b, 0x24, 0xe4, 0xc8, 0x2a,
	0xfc, 0x1f, 0x98, 0xbf, 0x65, 0xef, 0xe1, 0xe5, 0xcb, 0xe7, 0xd7, 0x5b, 0xe9, 0x2c, 0x3c, 0x36,
	0x17, 0xa4, 0xe2, 0x79, 0x77, 0x00, 0x9a, 0x75, 0xe3, 0xa7, 0x22, 0xcc, 0xe7, 0xd8, 0x3d, 0x40,
	0x75, 0xea, 0xc6, 0x35, 0xa8, 0xd8, 0xe3, 0x39, 0xf9, 0x09, 0x00, 0x00, 0xff, 0xff, 0x35, 0xca,
	0x0e, 0xdd, 0xb1, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WorkspaceTemplateServiceClient is the client API for WorkspaceTemplateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkspaceTemplateServiceClient interface {
	// Creates a Workflow
	CreateWorkspaceTemplate(ctx context.Context, in *CreateWorkspaceTemplateRequest, opts ...grpc.CallOption) (*WorkspaceTemplate, error)
}

type workspaceTemplateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkspaceTemplateServiceClient(cc grpc.ClientConnInterface) WorkspaceTemplateServiceClient {
	return &workspaceTemplateServiceClient{cc}
}

func (c *workspaceTemplateServiceClient) CreateWorkspaceTemplate(ctx context.Context, in *CreateWorkspaceTemplateRequest, opts ...grpc.CallOption) (*WorkspaceTemplate, error) {
	out := new(WorkspaceTemplate)
	err := c.cc.Invoke(ctx, "/api.WorkspaceTemplateService/CreateWorkspaceTemplate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkspaceTemplateServiceServer is the server API for WorkspaceTemplateService service.
type WorkspaceTemplateServiceServer interface {
	// Creates a Workflow
	CreateWorkspaceTemplate(context.Context, *CreateWorkspaceTemplateRequest) (*WorkspaceTemplate, error)
}

// UnimplementedWorkspaceTemplateServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWorkspaceTemplateServiceServer struct {
}

func (*UnimplementedWorkspaceTemplateServiceServer) CreateWorkspaceTemplate(ctx context.Context, req *CreateWorkspaceTemplateRequest) (*WorkspaceTemplate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWorkspaceTemplate not implemented")
}

func RegisterWorkspaceTemplateServiceServer(s *grpc.Server, srv WorkspaceTemplateServiceServer) {
	s.RegisterService(&_WorkspaceTemplateService_serviceDesc, srv)
}

func _WorkspaceTemplateService_CreateWorkspaceTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkspaceTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceTemplateServiceServer).CreateWorkspaceTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.WorkspaceTemplateService/CreateWorkspaceTemplate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceTemplateServiceServer).CreateWorkspaceTemplate(ctx, req.(*CreateWorkspaceTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WorkspaceTemplateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.WorkspaceTemplateService",
	HandlerType: (*WorkspaceTemplateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWorkspaceTemplate",
			Handler:    _WorkspaceTemplateService_CreateWorkspaceTemplate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workspace_template.proto",
}
