// Code generated by protoc-gen-go. DO NOT EDIT.
// source: workflow.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateWorkflowRequest struct {
	Namespace            string    `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Workflow             *Workflow `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateWorkflowRequest) Reset()         { *m = CreateWorkflowRequest{} }
func (m *CreateWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*CreateWorkflowRequest) ProtoMessage()    {}
func (*CreateWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{0}
}

func (m *CreateWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWorkflowRequest.Unmarshal(m, b)
}
func (m *CreateWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWorkflowRequest.Marshal(b, m, deterministic)
}
func (m *CreateWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWorkflowRequest.Merge(m, src)
}
func (m *CreateWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_CreateWorkflowRequest.Size(m)
}
func (m *CreateWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWorkflowRequest proto.InternalMessageInfo

func (m *CreateWorkflowRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *CreateWorkflowRequest) GetWorkflow() *Workflow {
	if m != nil {
		return m.Workflow
	}
	return nil
}

type Workflow struct {
	Uid                  string            `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Parameters           []*Parameter      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty"`
	WorkflowTemplate     *WorkflowTemplate `protobuf:"bytes,4,opt,name=workflowTemplate,proto3" json:"workflowTemplate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Workflow) Reset()         { *m = Workflow{} }
func (m *Workflow) String() string { return proto.CompactTextString(m) }
func (*Workflow) ProtoMessage()    {}
func (*Workflow) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{1}
}

func (m *Workflow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Workflow.Unmarshal(m, b)
}
func (m *Workflow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Workflow.Marshal(b, m, deterministic)
}
func (m *Workflow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Workflow.Merge(m, src)
}
func (m *Workflow) XXX_Size() int {
	return xxx_messageInfo_Workflow.Size(m)
}
func (m *Workflow) XXX_DiscardUnknown() {
	xxx_messageInfo_Workflow.DiscardUnknown(m)
}

var xxx_messageInfo_Workflow proto.InternalMessageInfo

func (m *Workflow) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Workflow) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Workflow) GetParameters() []*Parameter {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *Workflow) GetWorkflowTemplate() *WorkflowTemplate {
	if m != nil {
		return m.WorkflowTemplate
	}
	return nil
}

type Parameter struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Parameter) Reset()         { *m = Parameter{} }
func (m *Parameter) String() string { return proto.CompactTextString(m) }
func (*Parameter) ProtoMessage()    {}
func (*Parameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{2}
}

func (m *Parameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parameter.Unmarshal(m, b)
}
func (m *Parameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parameter.Marshal(b, m, deterministic)
}
func (m *Parameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parameter.Merge(m, src)
}
func (m *Parameter) XXX_Size() int {
	return xxx_messageInfo_Parameter.Size(m)
}
func (m *Parameter) XXX_DiscardUnknown() {
	xxx_messageInfo_Parameter.DiscardUnknown(m)
}

var xxx_messageInfo_Parameter proto.InternalMessageInfo

func (m *Parameter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Parameter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateWorkflowRequest)(nil), "api.CreateWorkflowRequest")
	proto.RegisterType((*Workflow)(nil), "api.Workflow")
	proto.RegisterType((*Parameter)(nil), "api.Parameter")
}

func init() { proto.RegisterFile("workflow.proto", fileDescriptor_892c7f566756b0be) }

var fileDescriptor_892c7f566756b0be = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0x53, 0x8a, 0x84, 0x0e, 0x11, 0xc9, 0x46, 0x62, 0xd3, 0x70, 0x20, 0xf5, 0x82, 0x97,
	0x36, 0x60, 0xb8, 0x78, 0x33, 0xbe, 0x80, 0xa9, 0x26, 0x1e, 0x75, 0xc0, 0x91, 0x54, 0x4b, 0x77,
	0xdd, 0x5d, 0xe0, 0x60, 0xb8, 0xf8, 0x0a, 0x3e, 0x82, 0x8f, 0xe4, 0x2b, 0xf8, 0x20, 0x86, 0x2d,
	0xbb, 0x42, 0xf4, 0x36, 0x9d, 0xf9, 0xfb, 0xcd, 0xbf, 0xff, 0x40, 0x7b, 0xc5, 0xe5, 0xcb, 0x53,
	0xc1, 0x57, 0x89, 0x90, 0x5c, 0x73, 0xe6, 0xa3, 0xc8, 0xa3, 0xde, 0x8c, 0xf3, 0x59, 0x41, 0x29,
	0x8a, 0x3c, 0xc5, 0xb2, 0xe4, 0x1a, 0x75, 0xce, 0x4b, 0x55, 0x49, 0xa2, 0x13, 0xfb, 0xcb, 0xbd,
	0xa6, 0xb9, 0x28, 0x50, 0x53, 0x35, 0x88, 0x1f, 0xa0, 0x7b, 0x25, 0x09, 0x35, 0xdd, 0x6d, 0x05,
	0x19, 0xbd, 0x2e, 0x48, 0x69, 0xd6, 0x83, 0xa0, 0xc4, 0x39, 0x29, 0x81, 0x53, 0x0a, 0xbd, 0xbe,
	0x37, 0x08, 0xb2, 0xdf, 0x06, 0x3b, 0x83, 0xa6, 0x25, 0x86, 0xb5, 0xbe, 0x37, 0x68, 0x8d, 0x0e,
	0x13, 0x14, 0x79, 0xe2, 0x28, 0x6e, 0x1c, 0x7f, 0x7a, 0xd0, 0xb4, 0x6d, 0xd6, 0x01, 0x7f, 0x91,
	0x3f, 0x6e, 0x79, 0x9b, 0x92, 0x31, 0xa8, 0x6f, 0xb0, 0x86, 0x12, 0x64, 0xa6, 0x66, 0x09, 0x80,
	0x40, 0x89, 0x73, 0xd2, 0x24, 0x55, 0xe8, 0xf7, 0xfd, 0x41, 0x6b, 0xd4, 0x36, 0xfc, 0x6b, 0xdb,
	0xce, 0x76, 0x14, 0xec, 0x12, 0x3a, 0x76, 0xdd, 0xed, 0xf6, 0x79, 0x61, 0xdd, 0xb8, 0xea, 0xee,
	0xb9, 0xb2, 0xc3, 0xec, 0x8f, 0x3c, 0x1e, 0x43, 0xe0, 0xd8, 0xce, 0x93, 0xb7, 0xe3, 0xe9, 0x18,
	0x0e, 0x96, 0x58, 0x2c, 0xac, 0xd1, 0xea, 0x63, 0xb4, 0x86, 0x23, 0x0b, 0xbf, 0x21, 0xb9, 0xcc,
	0xa7, 0xc4, 0x9e, 0xa1, 0x51, 0x25, 0xca, 0x22, 0xb3, 0xfc, 0xdf, 0x78, 0xa3, 0xfd, 0xb8, 0xe2,
	0xf1, 0xfb, 0xd7, 0xf7, 0x47, 0x2d, 0x8d, 0x4f, 0x37, 0xf7, 0x53, 0xe9, 0x72, 0x38, 0x21, 0x8d,
	0xc3, 0xf4, 0xcd, 0x25, 0xbe, 0x4e, 0xad, 0x65, 0x75, 0xe1, 0xb2, 0x9d, 0x34, 0xcc, 0x11, 0xcf,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x67, 0x35, 0xdb, 0xc1, 0x12, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WorkflowServiceClient is the client API for WorkflowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkflowServiceClient interface {
	// Creates a Workflow
	Create(ctx context.Context, in *CreateWorkflowRequest, opts ...grpc.CallOption) (*Workflow, error)
}

type workflowServiceClient struct {
	cc *grpc.ClientConn
}

func NewWorkflowServiceClient(cc *grpc.ClientConn) WorkflowServiceClient {
	return &workflowServiceClient{cc}
}

func (c *workflowServiceClient) Create(ctx context.Context, in *CreateWorkflowRequest, opts ...grpc.CallOption) (*Workflow, error) {
	out := new(Workflow)
	err := c.cc.Invoke(ctx, "/api.WorkflowService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowServiceServer is the server API for WorkflowService service.
type WorkflowServiceServer interface {
	// Creates a Workflow
	Create(context.Context, *CreateWorkflowRequest) (*Workflow, error)
}

// UnimplementedWorkflowServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWorkflowServiceServer struct {
}

func (*UnimplementedWorkflowServiceServer) Create(ctx context.Context, req *CreateWorkflowRequest) (*Workflow, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterWorkflowServiceServer(s *grpc.Server, srv WorkflowServiceServer) {
	s.RegisterService(&_WorkflowService_serviceDesc, srv)
}

func _WorkflowService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.WorkflowService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).Create(ctx, req.(*CreateWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WorkflowService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.WorkflowService",
	HandlerType: (*WorkflowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _WorkflowService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workflow.proto",
}
